import java.io.File;
import javax.swing.JFileChooser;

/*
 * Config.java
 *
 * Created on 7 de Fevereiro de 2005, 20:06
 */

/**
 *
 * @author Edison Puig Maldonado
 */

public class Config extends javax.swing.JPanel {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 4766671439349249698L;
	private SAPO sapo;
    private User user;
    
    /** Creates new form Config */
    public Config(SAPO sapo) {
        this.sapo = sapo;
        this.user = sapo.user;
        initComponents();
    }
    
    protected void mostraConfiguracoes() {
        if (user.dados.unidadecomprimento.equals("cm")) jrdoCm.doClick();
        if (user.dados.unidadecomprimento.equals("mm")) jrdoMm.doClick();
        if (user.dados.unidadecomprimento.equals("pol")) jrdoPol.doClick();
        if (user.dados.unidadeangulo.equals("graus")) jrdoGraus.doClick();
        if (user.dados.unidadeangulo.equals("radianos")) jrdoRadianos.doClick();
        jtfDB.setText(sapo.dbDirPath);
        jtfImgTrab.setText(sapo.figDirPath);
        jtfProjetos.setText(user.dados.dirprojetos);
        jtfImagens.setText(user.dados.dirimagens);
        jtfRelatorios.setText(user.dados.dirrelatorios);
        jtfBackup.setText(user.dados.dirbackup);
        if (user.dados.boasvindas) jcbMostraBoasVindas.setSelected(true);
        if (user.dados.mostradicas) jcbMostraDicas.setSelected(true);
        // if (user.dados.idioma.equals("pt")) jcbLinguagem.setSelected("Português");
        jtfSMTP.setText(user.dados.servidoremail);
        jtfUserSMTP.setText(user.dados.useremail);
        jtfSMTP.setText(user.dados.servidoremail);
        jpfSenhaEmail.setText(user.dados.senhaemail);
        jtfNomeCompleto.setText(user.dados.nomecompleto);
        if (user.dados.autentica) jcbAutenticar.setSelected(true);
        jtfSAPOUser.setText(user.dados.username);
        jpfSAPO.setText(user.dados.senha);
    }
    
    private void setUserDadosConfig() {
        user.dados.boasvindas = jcbMostraBoasVindas.isSelected();
        user.dados.mostradicas = jcbMostraDicas.isSelected();
        if (jrdoCm.isSelected()) user.dados.unidadecomprimento = "cm";
        if (jrdoMm.isSelected()) user.dados.unidadecomprimento = "mm";
        if (jrdoPol.isSelected()) user.dados.unidadecomprimento = "pol";
        if (jrdoGraus.isSelected()) user.dados.unidadeangulo = "graus";
        if (jrdoRadianos.isSelected()) user.dados.unidadeangulo = "radianos";
        user.dados.decimalNumbersFormat = Integer.parseInt(jtxtNumFormat.getText());
        user.dados.dirprojetos = jtfProjetos.getText();
        user.dados.dirimagens =jtfImagens.getText();
        user.dados.dirrelatorios = jtfRelatorios.getText();
        user.dados.dirbackup = jtfBackup.getText();
        // idioma
        user.dados.servidoremail = jtfSMTP.getText();
        user.dados.useremail = jtfUserSMTP.getText();
        user.dados.servidoremail = jtfSMTP.getText();
        user.dados.senhaemail = String.copyValueOf(jpfSenhaEmail.getPassword());
        user.dados.nomecompleto = jtfNomeCompleto.getText();
        user.dados.autentica = jcbAutenticar.isSelected();
        user.dados.username = jtfSAPOUser.getText();
        user.dados.senha = String.copyValueOf(jpfSAPO.getPassword());
    }
    
    private String escolhePasta(String title, String path) {
        String strAux;
        JFileChooser fc = new JFileChooser();
        fc.setDialogTitle(title);
        File filePath = new File(path);
        if ((path != null) && (path.length() > 0) && (filePath.exists())) fc.setCurrentDirectory(filePath);
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fc.showOpenDialog(sapo);
        if(returnVal == JFileChooser.APPROVE_OPTION)
            strAux = fc.getSelectedFile().getAbsolutePath();
        else strAux = "";
        return strAux;
    }
    
    private void conferePastasDeTrabalho() {
    	if (!sapo.dbDirPath.equalsIgnoreCase(jtfDB.getText())) {
    		sapo.setDBDirPath(jtfDB.getText());
    	}
    	if (!sapo.figDirPath.equalsIgnoreCase(jtfImgTrab.getText())) {
    		sapo.setFigDirPath(jtfImgTrab.getText());
    	}
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        btnGroupComprimento = new javax.swing.ButtonGroup();
        buttonGroupAngulo = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jbtnConfgOk = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jbtnConfgCancel = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpnlDiretorios = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel43 = new javax.swing.JPanel();
        jtfDB = new javax.swing.JTextField();
        jButtonDB = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel44 = new javax.swing.JPanel();
        jtfImgTrab = new javax.swing.JTextField();
        jButtonImgTrab = new javax.swing.JButton();
        jPanel45 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel40 = new javax.swing.JPanel();
        jtfImagens = new javax.swing.JTextField();
        jButtonImagens = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel41 = new javax.swing.JPanel();
        jtfRelatorios = new javax.swing.JTextField();
        jButtonRelatorios = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel39 = new javax.swing.JPanel();
        jtfProjetos = new javax.swing.JTextField();
        jButtonProjetos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel42 = new javax.swing.JPanel();
        jtfBackup = new javax.swing.JTextField();
        jButtonBackup = new javax.swing.JButton();
        jpnlDimesoes = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jrdoMm = new javax.swing.JRadioButton();
        jrdoCm = new javax.swing.JRadioButton();
        jrdoPol = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jrdoGraus = new javax.swing.JRadioButton();
        jrdoRadianos = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jtxtNumFormat = new javax.swing.JTextField();
        jpnOutrosConf = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel38 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jcbMostraBoasVindas = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jcbMostraDicas = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jcbLinguagem = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jtfSMTP = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtfUserSMTP = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtfNomeCompleto = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jPanel31 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jpfSenhaEmail = new javax.swing.JPasswordField();
        jPanel52 = new javax.swing.JPanel();
        jPanel54 = new javax.swing.JPanel();
        jPanel55 = new javax.swing.JPanel();
        jpnSeguranca = new javax.swing.JPanel();
        jPanel49 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jPanel50 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jPanel51 = new javax.swing.JPanel();
        jcbAutenticar = new javax.swing.JCheckBox();
        jLabel57 = new javax.swing.JLabel();
        jtfSAPOUser = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jpfSAPO = new javax.swing.JPasswordField();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        setMinimumSize(new java.awt.Dimension(560, 515));
        setPreferredSize(new java.awt.Dimension(560, 480));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jPanel4.setFocusable(false);
        jPanel4.setMinimumSize(new java.awt.Dimension(350, 40));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(350, 35));
        jbtnConfgOk.setText("Ok");
        jbtnConfgOk.setFocusCycleRoot(true);
        jbtnConfgOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfgOkActionPerformed(evt);
            }
        });

        jPanel4.add(jbtnConfgOk);

        jButton7.setText("Aplicar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel4.add(jButton7);

        jbtnConfgCancel.setText("Cancela");
        jbtnConfgCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfgCancelActionPerformed(evt);
            }
        });

        jPanel4.add(jbtnConfgCancel);

        add(jPanel4, java.awt.BorderLayout.SOUTH);

        jpnlDiretorios.setLayout(new java.awt.BorderLayout());

        jPanel35.setLayout(new java.awt.GridBagLayout());

        jPanel35.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14));
        jPanel35.setMinimumSize(new java.awt.Dimension(40, 100));
        jPanel35.setOpaque(false);
        jPanel35.setPreferredSize(new java.awt.Dimension(40, 100));
        jLabel22.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Configurar pastas e diret\u00f3rios");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        jPanel35.add(jLabel22, gridBagConstraints);

        jLabel23.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("de trabalho do programa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanel35.add(jLabel23, gridBagConstraints);

        jpnlDiretorios.add(jPanel35, java.awt.BorderLayout.NORTH);

        jPanel36.setLayout(new java.awt.GridBagLayout());

        jPanel36.setPreferredSize(new java.awt.Dimension(312, 200));
        jPanel46.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14));
        jPanel46.setMinimumSize(new java.awt.Dimension(40, 100));
        jPanel46.setOpaque(false);
        jPanel46.setPreferredSize(new java.awt.Dimension(40, 40));
        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 13));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Configure os diret\u00f3rios principais de trabalho do SAPO :");
        jPanel46.add(jLabel33);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel36.add(jPanel46, gridBagConstraints);

        jLabel7.setText("Banco de Dados :   ");
        jLabel7.setToolTipText("Define a pasta de trabalho para o banco de dados do programa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel36.add(jLabel7, gridBagConstraints);

        jPanel43.setLayout(new java.awt.GridBagLayout());

        jPanel43.setToolTipText("Define a pasta de trabalho para o banco de dados do programa");
        jtfDB.setToolTipText("Define a pasta de trabalho para o banco de dados do programa");
        jtfDB.setMinimumSize(new java.awt.Dimension(330, 20));
        jtfDB.setPreferredSize(new java.awt.Dimension(330, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel43.add(jtfDB, gridBagConstraints);

        jButtonDB.setText("Procurar");
        jButtonDB.setToolTipText("Define a pasta de trabalho para o banco de dados do programa");
        jButtonDB.setMargin(new java.awt.Insets(0, 4, 0, 4));
        jButtonDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDBActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        jPanel43.add(jButtonDB, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        jPanel36.add(jPanel43, gridBagConstraints);

        jLabel8.setText("Imagens (trabalho) :   ");
        jLabel8.setToolTipText("Define a pasta de trabalho onde imagens de projetos ser\u00e3o salvas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel36.add(jLabel8, gridBagConstraints);

        jPanel44.setLayout(new java.awt.GridBagLayout());

        jPanel44.setToolTipText("Define a pasta de trabalho onde imagens de projetos ser\u00e3o salvas");
        jtfImgTrab.setToolTipText("Define a pasta de trabalho onde imagens de projetos ser\u00e3o salvas");
        jtfImgTrab.setMinimumSize(new java.awt.Dimension(330, 20));
        jtfImgTrab.setPreferredSize(new java.awt.Dimension(330, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel44.add(jtfImgTrab, gridBagConstraints);

        jButtonImgTrab.setText("Procurar");
        jButtonImgTrab.setToolTipText("Define a pasta de trabalho onde imagens de projetos ser\u00e3o salvas");
        jButtonImgTrab.setMargin(new java.awt.Insets(0, 4, 0, 4));
        jButtonImgTrab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImgTrabActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        jPanel44.add(jButtonImgTrab, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        jPanel36.add(jPanel44, gridBagConstraints);

        jPanel45.setLayout(new java.awt.GridBagLayout());

        jPanel45.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14));
        jPanel45.setMinimumSize(new java.awt.Dimension(40, 100));
        jPanel45.setOpaque(false);
        jPanel45.setPreferredSize(new java.awt.Dimension(40, 60));
        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 13));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Configure as pastas onde mais freq\u00fcentemente s\u00e3o encontrados :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        jPanel45.add(jLabel31, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel36.add(jPanel45, gridBagConstraints);

        jLabel1.setText("Pasta de Imagens : ");
        jLabel1.setToolTipText("Define a pasta de onde imagens ser\u00e3o importadas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel36.add(jLabel1, gridBagConstraints);

        jPanel40.setLayout(new java.awt.GridBagLayout());

        jPanel40.setToolTipText("Define a pasta de onde imagens ser\u00e3o importadas");
        jtfImagens.setToolTipText("Define a pasta de onde imagens ser\u00e3o importadas");
        jtfImagens.setMinimumSize(new java.awt.Dimension(330, 20));
        jtfImagens.setPreferredSize(new java.awt.Dimension(330, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel40.add(jtfImagens, gridBagConstraints);

        jButtonImagens.setText("Procurar");
        jButtonImagens.setToolTipText("Define a pasta de onde imagens ser\u00e3o importadas");
        jButtonImagens.setMargin(new java.awt.Insets(0, 4, 0, 4));
        jButtonImagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImagensActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        jPanel40.add(jButtonImagens, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        jPanel36.add(jPanel40, gridBagConstraints);

        jLabel2.setText("Pasta de Relat\u00f3rios : ");
        jLabel2.setToolTipText("Define a pasta onde relat\u00f3rios ser\u00e3o salvos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel36.add(jLabel2, gridBagConstraints);

        jPanel41.setLayout(new java.awt.GridBagLayout());

        jPanel41.setToolTipText("Define a pasta onde relat\u00f3rios ser\u00e3o salvos");
        jtfRelatorios.setToolTipText("Define a pasta onde relat\u00f3rios ser\u00e3o salvos");
        jtfRelatorios.setMinimumSize(new java.awt.Dimension(330, 20));
        jtfRelatorios.setPreferredSize(new java.awt.Dimension(330, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel41.add(jtfRelatorios, gridBagConstraints);

        jButtonRelatorios.setText("Procurar");
        jButtonRelatorios.setToolTipText("Define a pasta onde relat\u00f3rios ser\u00e3o salvos");
        jButtonRelatorios.setMargin(new java.awt.Insets(0, 4, 0, 4));
        jButtonRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatoriosActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        jPanel41.add(jButtonRelatorios, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        jPanel36.add(jPanel41, gridBagConstraints);

        jLabel3.setText("Pasta de Projetos : ");
        jLabel3.setToolTipText("Define a pasta onde projetos exportados em arquivo ser\u00e3o salvos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel36.add(jLabel3, gridBagConstraints);

        jPanel39.setLayout(new java.awt.GridBagLayout());

        jtfProjetos.setToolTipText("Define a pasta onde projetos exportados em arquivo ser\u00e3o salvos");
        jtfProjetos.setMinimumSize(new java.awt.Dimension(330, 20));
        jtfProjetos.setPreferredSize(new java.awt.Dimension(330, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel39.add(jtfProjetos, gridBagConstraints);

        jButtonProjetos.setText("Procurar");
        jButtonProjetos.setToolTipText("Define a pasta onde projetos exportados em arquivo ser\u00e3o salvos");
        jButtonProjetos.setMargin(new java.awt.Insets(0, 4, 0, 4));
        jButtonProjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProjetosActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanel39.add(jButtonProjetos, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        jPanel36.add(jPanel39, gridBagConstraints);

        jLabel4.setText("Pasta de Backup :  ");
        jLabel4.setToolTipText("Define a pasta onde ser\u00e3o salvos backups");
        jLabel4.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        jPanel36.add(jLabel4, gridBagConstraints);

        jPanel42.setLayout(new java.awt.GridBagLayout());

        jPanel42.setToolTipText("Define a pasta onde ser\u00e3o salvos backups");
        jtfBackup.setToolTipText("Define a pasta onde ser\u00e3o salvos backups");
        jtfBackup.setEnabled(false);
        jtfBackup.setMinimumSize(new java.awt.Dimension(330, 20));
        jtfBackup.setPreferredSize(new java.awt.Dimension(330, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel42.add(jtfBackup, gridBagConstraints);

        jButtonBackup.setText("Procurar");
        jButtonBackup.setToolTipText("Define a pasta onde ser\u00e3o salvos backups");
        jButtonBackup.setEnabled(false);
        jButtonBackup.setMargin(new java.awt.Insets(0, 4, 0, 4));
        jButtonBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackupActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        jPanel42.add(jButtonBackup, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        jPanel36.add(jPanel42, gridBagConstraints);

        jpnlDiretorios.add(jPanel36, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Diret\u00f3rios", jpnlDiretorios);

        jpnlDimesoes.setLayout(new java.awt.BorderLayout());

        jPanel33.setLayout(new java.awt.GridBagLayout());

        jPanel33.setMinimumSize(new java.awt.Dimension(40, 80));
        jPanel33.setOpaque(false);
        jPanel33.setPreferredSize(new java.awt.Dimension(40, 100));
        jLabel26.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Configurar as unidades que ser\u00e3o usadas ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        jPanel33.add(jLabel26, gridBagConstraints);

        jLabel27.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("para escalas, an\u00e1lises e relat\u00f3rios  :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanel33.add(jLabel27, gridBagConstraints);

        jpnlDimesoes.add(jPanel33, java.awt.BorderLayout.NORTH);

        jPanel34.setLayout(new java.awt.GridBagLayout());

        jPanel34.setMinimumSize(new java.awt.Dimension(40, 100));
        jPanel34.setPreferredSize(new java.awt.Dimension(40, 200));
        jLabel19.setText("Unidade de comprimento : ");
        jLabel19.setFocusCycleRoot(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel34.add(jLabel19, gridBagConstraints);

        btnGroupComprimento.add(jrdoMm);
        jrdoMm.setText("Mil\u00edmetros");
        jrdoMm.setEnabled(false);
        jPanel14.add(jrdoMm);

        btnGroupComprimento.add(jrdoCm);
        jrdoCm.setText("Cent\u00edmetros");
        jrdoCm.setFocusCycleRoot(true);
        jPanel14.add(jrdoCm);

        btnGroupComprimento.add(jrdoPol);
        jrdoPol.setText("Polegadas");
        jrdoPol.setEnabled(false);
        jPanel14.add(jrdoPol);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 6, 6);
        jPanel34.add(jPanel14, gridBagConstraints);

        jLabel20.setText("Unidade de \u00e2ngulo : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel34.add(jLabel20, gridBagConstraints);

        buttonGroupAngulo.add(jrdoGraus);
        jrdoGraus.setText("Graus");
        jPanel32.add(jrdoGraus);

        buttonGroupAngulo.add(jrdoRadianos);
        jrdoRadianos.setText("Radianos");
        jrdoRadianos.setEnabled(false);
        jPanel32.add(jrdoRadianos);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 6, 6);
        jPanel34.add(jPanel32, gridBagConstraints);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Casas decimais:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel34.add(jLabel6, gridBagConstraints);

        jtxtNumFormat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtNumFormat.setText("1");
        jtxtNumFormat.setPreferredSize(new java.awt.Dimension(25, 20));
        jPanel3.add(jtxtNumFormat);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 6, 6);
        jPanel34.add(jPanel3, gridBagConstraints);

        jpnlDimesoes.add(jPanel34, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Dimens\u00f5es", jpnlDimesoes);

        jpnOutrosConf.setLayout(new java.awt.BorderLayout());

        jPanel37.setLayout(new java.awt.GridBagLayout());

        jPanel37.setMinimumSize(new java.awt.Dimension(40, 100));
        jPanel37.setOpaque(false);
        jPanel37.setPreferredSize(new java.awt.Dimension(40, 100));
        jLabel24.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Configurar op\u00e7\u00f5es de ajuda,");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        jPanel37.add(jLabel24, gridBagConstraints);

        jLabel25.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("envio de relat\u00f3rios de erros e outros.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanel37.add(jLabel25, gridBagConstraints);

        jpnOutrosConf.add(jPanel37, java.awt.BorderLayout.NORTH);

        jPanel38.setLayout(new java.awt.GridBagLayout());

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("Mostrar tela de boas vindas ? ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel38.add(jLabel28, gridBagConstraints);

        jcbMostraBoasVindas.setText("Mostrar");
        jPanel11.add(jcbMostraBoasVindas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel38.add(jPanel11, gridBagConstraints);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Mostrar dicas ? ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel38.add(jLabel21, gridBagConstraints);

        jcbMostraDicas.setText("Mostrar");
        jPanel2.add(jcbMostraDicas);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel38.add(jPanel2, gridBagConstraints);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Idioma : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel38.add(jLabel5, gridBagConstraints);

        jcbLinguagem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Português", "English", "Español", "Italiano", "Français", "Deutsch" }));
        jcbLinguagem.setMaximumSize(new java.awt.Dimension(150, 999));
        jcbLinguagem.setMinimumSize(new java.awt.Dimension(330, 20));
        jcbLinguagem.setPreferredSize(new java.awt.Dimension(330, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel38.add(jcbLinguagem, gridBagConstraints);

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Servidor de e-mail (SMTP) :   ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel38.add(jLabel16, gridBagConstraints);

        jtfSMTP.setMaximumSize(new java.awt.Dimension(150, 999));
        jtfSMTP.setMinimumSize(new java.awt.Dimension(330, 20));
        jtfSMTP.setPreferredSize(new java.awt.Dimension(330, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel38.add(jtfSMTP, gridBagConstraints);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Nome de usu\u00e1rio (E-mail) :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel38.add(jLabel17, gridBagConstraints);

        jtfUserSMTP.setMaximumSize(new java.awt.Dimension(150, 999));
        jtfUserSMTP.setMinimumSize(new java.awt.Dimension(330, 20));
        jtfUserSMTP.setPreferredSize(new java.awt.Dimension(330, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel38.add(jtfUserSMTP, gridBagConstraints);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Seu nome :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel38.add(jLabel18, gridBagConstraints);

        jtfNomeCompleto.setMaximumSize(new java.awt.Dimension(150, 999));
        jtfNomeCompleto.setMinimumSize(new java.awt.Dimension(330, 20));
        jtfNomeCompleto.setPreferredSize(new java.awt.Dimension(330, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel38.add(jtfNomeCompleto, gridBagConstraints);

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel38.add(jLabel29, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel38.add(jPanel31, gridBagConstraints);

        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setText("Senha de email (SMTP) :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel38.add(jLabel30, gridBagConstraints);

        jpfSenhaEmail.setMaximumSize(new java.awt.Dimension(150, 999));
        jpfSenhaEmail.setMinimumSize(new java.awt.Dimension(330, 20));
        jpfSenhaEmail.setPreferredSize(new java.awt.Dimension(330, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel38.add(jpfSenhaEmail, gridBagConstraints);

        jpnOutrosConf.add(jPanel38, java.awt.BorderLayout.CENTER);

        jPanel52.setMinimumSize(new java.awt.Dimension(10, 30));
        jPanel52.setPreferredSize(new java.awt.Dimension(10, 30));
        jpnOutrosConf.add(jPanel52, java.awt.BorderLayout.SOUTH);

        jPanel54.setMinimumSize(new java.awt.Dimension(30, 10));
        jPanel54.setPreferredSize(new java.awt.Dimension(40, 10));
        jpnOutrosConf.add(jPanel54, java.awt.BorderLayout.EAST);

        jPanel55.setMinimumSize(new java.awt.Dimension(30, 10));
        jPanel55.setPreferredSize(new java.awt.Dimension(40, 10));
        jpnOutrosConf.add(jPanel55, java.awt.BorderLayout.WEST);

        jTabbedPane1.addTab("Ajuda e Erros", jpnOutrosConf);

        jpnSeguranca.setLayout(new java.awt.BorderLayout());

        jPanel49.setLayout(new java.awt.GridBagLayout());

        jPanel49.setMinimumSize(new java.awt.Dimension(40, 100));
        jPanel49.setPreferredSize(new java.awt.Dimension(40, 100));
        jLabel51.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Configurar op\u00e7\u00f5es de seguran\u00e7a, acesso ao programa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        jPanel49.add(jLabel51, gridBagConstraints);

        jLabel54.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 16));
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("e acesso \u00e0 base de dados nacional.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel49.add(jLabel54, gridBagConstraints);

        jpnSeguranca.add(jPanel49, java.awt.BorderLayout.NORTH);

        jPanel50.setLayout(new java.awt.GridBagLayout());

        jPanel50.setMinimumSize(new java.awt.Dimension(350, 150));
        jPanel50.setPreferredSize(new java.awt.Dimension(350, 200));
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel53.setText("Autenticar no in\u00edcio do programa? ");
        jPanel1.add(jLabel53);

        jcbAutenticar.setText("Autenticar");
        jcbAutenticar.setEnabled(false);
        jPanel51.add(jcbAutenticar);

        jPanel1.add(jPanel51);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        jPanel50.add(jPanel1, gridBagConstraints);

        jLabel57.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel57.setText("Nome de usu\u00e1rio :  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        jPanel50.add(jLabel57, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        jPanel50.add(jtfSAPOUser, gridBagConstraints);

        jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel60.setText("Senha de acesso :  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel50.add(jLabel60, gridBagConstraints);

        jpfSAPO.setMinimumSize(new java.awt.Dimension(6, 20));
        jpfSAPO.setPreferredSize(new java.awt.Dimension(6, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        jPanel50.add(jpfSAPO, gridBagConstraints);

        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("Este nome de usu\u00e1rio e senha de acesso");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(12, 0, 0, 0);
        jPanel50.add(jLabel55, gridBagConstraints);

        jLabel56.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel56.setText("ser\u00e3o tamb\u00e9m usados para acesso e publica\u00e7\u00e3o");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        jPanel50.add(jLabel56, gridBagConstraints);

        jLabel58.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel58.setText("de dados na base de dados nacional.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        jPanel50.add(jLabel58, gridBagConstraints);

        jpnSeguranca.add(jPanel50, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Seguran\u00e7a", jpnSeguranca);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents

    private void jButtonImgTrabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImgTrabActionPerformed
        jtfImgTrab.setText(escolhePasta("SAPO - Imagens (trabalho)", jtfImgTrab.getText()));
        sapo.setFigDirPath(jtfImgTrab.getText());
    }//GEN-LAST:event_jButtonImgTrabActionPerformed

    private void jButtonDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDBActionPerformed
        jtfDB.setText(escolhePasta("SAPO - Banco de Dados", jtfDB.getText()));
        sapo.setDBDirPath(jtfDB.getText());
    }//GEN-LAST:event_jButtonDBActionPerformed

    private void jButtonBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackupActionPerformed
        jtfBackup.setText(escolhePasta("SAPO - Backup", jtfBackup.getText()));
        user.dados.dirbackup = jtfBackup.getText();
    }//GEN-LAST:event_jButtonBackupActionPerformed

    private void jButtonRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatoriosActionPerformed
        jtfRelatorios.setText(escolhePasta("SAPO - Relatórios", jtfRelatorios.getText()));
        user.dados.dirrelatorios = jtfRelatorios.getText();
    }//GEN-LAST:event_jButtonRelatoriosActionPerformed

    private void jButtonImagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImagensActionPerformed
        jtfImagens.setText(escolhePasta("SAPO - Imagens (importação)", jtfImagens.getText()));
        user.dados.dirimagens = jtfImagens.getText();
    }//GEN-LAST:event_jButtonImagensActionPerformed

    private void jButtonProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProjetosActionPerformed
        jtfProjetos.setText(escolhePasta("SAPO - Projetos (exportação)", jtfProjetos.getText()));
        user.dados.dirprojetos = jtfProjetos.getText();
    }//GEN-LAST:event_jButtonProjetosActionPerformed

    private void jbtnConfgCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConfgCancelActionPerformed
        sapo.jDialogSAPO.setVisible(false);
        sapo.jDialogSAPO.close();
    }//GEN-LAST:event_jbtnConfgCancelActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    	setUserDadosConfig();
        user.escreveDB();
        conferePastasDeTrabalho();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jbtnConfgOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConfgOkActionPerformed
    	setUserDadosConfig();
        user.escreveDB();
        sapo.jDialogSAPO.setVisible(false);
        sapo.jDialogSAPO.close();
        conferePastasDeTrabalho();
    }//GEN-LAST:event_jbtnConfgOkActionPerformed
    
    public int getDecimalNumbers(){
        return Integer.parseInt(jtxtNumFormat.getText());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupComprimento;
    private javax.swing.ButtonGroup buttonGroupAngulo;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonBackup;
    private javax.swing.JButton jButtonDB;
    private javax.swing.JButton jButtonImagens;
    private javax.swing.JButton jButtonImgTrab;
    private javax.swing.JButton jButtonProjetos;
    private javax.swing.JButton jButtonRelatorios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtnConfgCancel;
    private javax.swing.JButton jbtnConfgOk;
    private javax.swing.JCheckBox jcbAutenticar;
    private javax.swing.JComboBox jcbLinguagem;
    private javax.swing.JCheckBox jcbMostraBoasVindas;
    private javax.swing.JCheckBox jcbMostraDicas;
    private javax.swing.JPasswordField jpfSAPO;
    protected javax.swing.JPasswordField jpfSenhaEmail;
    private javax.swing.JPanel jpnOutrosConf;
    private javax.swing.JPanel jpnSeguranca;
    private javax.swing.JPanel jpnlDimesoes;
    private javax.swing.JPanel jpnlDiretorios;
    private javax.swing.JRadioButton jrdoCm;
    private javax.swing.JRadioButton jrdoGraus;
    private javax.swing.JRadioButton jrdoMm;
    private javax.swing.JRadioButton jrdoPol;
    private javax.swing.JRadioButton jrdoRadianos;
    private javax.swing.JTextField jtfBackup;
    private javax.swing.JTextField jtfDB;
    private javax.swing.JTextField jtfImagens;
    private javax.swing.JTextField jtfImgTrab;
    protected javax.swing.JTextField jtfNomeCompleto;
    private javax.swing.JTextField jtfProjetos;
    private javax.swing.JTextField jtfRelatorios;
    private javax.swing.JTextField jtfSAPOUser;
    protected javax.swing.JTextField jtfSMTP;
    protected javax.swing.JTextField jtfUserSMTP;
    private javax.swing.JTextField jtxtNumFormat;
    // End of variables declaration//GEN-END:variables
    
}
