import java.awt.SystemColor;

import javax.swing.JOptionPane;

/*
 * FerramentasDesenhoPanel.java
 *
 * Created on 5 de Julho de 2005, 22:38
 */
/**
 *
 * @author  Administrador
 */
public class FerramentasImagemPanel extends javax.swing.JPanel {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 8982644079238958056L;
	SAPO sapo;
    
    
    /** Creates new form FerramentasDesenhoPanel */
    public FerramentasImagemPanel(SAPO sapo) {
        this.sapo = sapo;
        SAPO.setLookAndFeel(this);
        initComponents();
    }

    public void resetComponents() {
    	kernelBox.setSelectedIndex(0);
    	jSliderBlurSharp.setValue(150);
    }
    
    public void setEnabledAll(boolean op) {
    	jbtnSolUp.setEnabled(op);
		jbtnSolDown.setEnabled(op);
		jbtnContrUp.setEnabled(op);
		jbtnContrDown.setEnabled(op);
		jbtnFlipH.setEnabled(op);
		jbtnFlipV.setEnabled(op);
		jbtnRot270.setEnabled(op);
		jbtnRot90.setEnabled(op);
		jbtnCrop.setEnabled(op);
		jSliderBlurSharp.setEnabled(op);
		kernelBox.setEnabled(op);
    }
    
    public void setEnabled(String area, boolean op) {
    	jbtnOkImage.setBackground(SystemColor.controlHighlight);
    	if (area.equalsIgnoreCase("brilho")) {
    		jbtnSolUp.setEnabled(op);
    		jbtnSolDown.setEnabled(op);
    	}
    	if (area.equalsIgnoreCase("contraste")) {
    		jbtnContrUp.setEnabled(op);
    		jbtnContrDown.setEnabled(op);
    	}
    	if (area.equalsIgnoreCase("crop")) {
    		jbtnCrop.setEnabled(op);
    	}
    	if (area.equalsIgnoreCase("flip")) {
    		jbtnFlipH.setEnabled(op);
    		jbtnFlipV.setEnabled(op);
    		jbtnRot270.setEnabled(op);
    		jbtnRot90.setEnabled(op);
    	}
    	if (area.equalsIgnoreCase("blursharp")) 
    		jSliderBlurSharp.setEnabled(op);
    	if (area.equalsIgnoreCase("gradient")) 
    		kernelBox.setEnabled(op);
    	jbtnOkImage.requestFocus();
    }
    
    private final int FLIP_HORIZONTAL = 1;
    private final int FLIP_VERTICAL = 2;
    private final int ROTATE_90 = 3;
    private final int ROTATE_270 = 4;
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        btnGroupImagem = new javax.swing.ButtonGroup();
        toolBar = new javax.swing.JToolBar();
        jbtnSolUp = new javax.swing.JButton();
        jbtnSolDown = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jbtnContrUp = new javax.swing.JButton();
        jbtnContrDown = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jbtnRot90 = new javax.swing.JButton();
        jbtnRot270 = new javax.swing.JButton();
        jbtnFlipH = new javax.swing.JButton();
        jbtnFlipV = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbtnCrop = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanelFoco = new javax.swing.JPanel();
        jSliderBlurSharp = new javax.swing.JSlider();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanelGradient = new javax.swing.JPanel();
        kernelBox = new javax.swing.JComboBox();
        jPanel9 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jbtnOkImage = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        toolBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        toolBar.setFloatable(false);
        toolBar.setRollover(true);
        toolBar.setToolTipText("");
        toolBar.setAlignmentX(0.0F);
        toolBar.setMaximumSize(new java.awt.Dimension(9999, 9999));
        toolBar.setMinimumSize(new java.awt.Dimension(28, 28));
        toolBar.setName("SAPO - Ferramentas");
        jbtnSolUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/solup.gif")));
        jbtnSolUp.setToolTipText("Aumentar brilho");
        jbtnSolUp.setMaximumSize(new java.awt.Dimension(30, 30));
        jbtnSolUp.setMinimumSize(new java.awt.Dimension(30, 30));
        jbtnSolUp.setPreferredSize(new java.awt.Dimension(30, 30));
        jbtnSolUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSolUpActionPerformed(evt);
            }
        });

        toolBar.add(jbtnSolUp);

        jbtnSolDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/soldown.gif")));
        jbtnSolDown.setToolTipText("Reduzir brilho");
        jbtnSolDown.setMaximumSize(new java.awt.Dimension(30, 30));
        jbtnSolDown.setMinimumSize(new java.awt.Dimension(30, 30));
        jbtnSolDown.setPreferredSize(new java.awt.Dimension(30, 30));
        jbtnSolDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSolDownActionPerformed(evt);
            }
        });

        toolBar.add(jbtnSolDown);

        jPanel5.setMaximumSize(new java.awt.Dimension(15, 32767));
        jPanel5.setOpaque(false);
        jPanel5.setPreferredSize(new java.awt.Dimension(15, 10));
        toolBar.add(jPanel5);

        jbtnContrUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/contrup.gif")));
        jbtnContrUp.setToolTipText("Aumentar contraste");
        jbtnContrUp.setMaximumSize(new java.awt.Dimension(30, 30));
        jbtnContrUp.setMinimumSize(new java.awt.Dimension(30, 30));
        jbtnContrUp.setPreferredSize(new java.awt.Dimension(30, 30));
        jbtnContrUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnContrUpActionPerformed(evt);
            }
        });

        toolBar.add(jbtnContrUp);

        jbtnContrDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/contrdown.gif")));
        jbtnContrDown.setToolTipText("Reduzir contraste");
        jbtnContrDown.setMaximumSize(new java.awt.Dimension(30, 30));
        jbtnContrDown.setMinimumSize(new java.awt.Dimension(30, 30));
        jbtnContrDown.setPreferredSize(new java.awt.Dimension(30, 30));
        jbtnContrDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnContrDownActionPerformed(evt);
            }
        });

        toolBar.add(jbtnContrDown);

        jPanel1.setMaximumSize(new java.awt.Dimension(15, 32767));
        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(15, 10));
        toolBar.add(jPanel1);

        jbtnRot90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/90+.gif")));
        jbtnRot90.setToolTipText("Girar imagem 90\u00ba no sentido hor\u00e1rio");
        jbtnRot90.setMaximumSize(new java.awt.Dimension(30, 30));
        jbtnRot90.setMinimumSize(new java.awt.Dimension(30, 30));
        jbtnRot90.setPreferredSize(new java.awt.Dimension(30, 30));
        jbtnRot90.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRot90ActionPerformed(evt);
            }
        });

        toolBar.add(jbtnRot90);

        jbtnRot270.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/90-.gif")));
        jbtnRot270.setToolTipText("Girar imagem 90\u00ba no sentido anti-hor\u00e1rio");
        jbtnRot270.setMaximumSize(new java.awt.Dimension(30, 30));
        jbtnRot270.setMinimumSize(new java.awt.Dimension(30, 30));
        jbtnRot270.setPreferredSize(new java.awt.Dimension(30, 30));
        jbtnRot270.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRot270ActionPerformed(evt);
            }
        });

        toolBar.add(jbtnRot270);

        jbtnFlipH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/FLIP_H.gif")));
        jbtnFlipH.setToolTipText("Espelhar a imagem na horizontal");
        jbtnFlipH.setMaximumSize(new java.awt.Dimension(30, 30));
        jbtnFlipH.setMinimumSize(new java.awt.Dimension(30, 30));
        jbtnFlipH.setPreferredSize(new java.awt.Dimension(30, 30));
        jbtnFlipH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFlipHActionPerformed(evt);
            }
        });

        toolBar.add(jbtnFlipH);

        jbtnFlipV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/FLIP_V.gif")));
        jbtnFlipV.setToolTipText("Espelhar a imagem na vertical");
        jbtnFlipV.setMaximumSize(new java.awt.Dimension(30, 30));
        jbtnFlipV.setMinimumSize(new java.awt.Dimension(30, 30));
        jbtnFlipV.setPreferredSize(new java.awt.Dimension(30, 30));
        jbtnFlipV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFlipVActionPerformed(evt);
            }
        });

        toolBar.add(jbtnFlipV);

        jPanel2.setMaximumSize(new java.awt.Dimension(15, 32767));
        jPanel2.setOpaque(false);
        toolBar.add(jPanel2);

        jbtnCrop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/crop.gif")));
        jbtnCrop.setToolTipText("Cortar imagem");
        jbtnCrop.setMaximumSize(new java.awt.Dimension(30, 30));
        jbtnCrop.setMinimumSize(new java.awt.Dimension(30, 30));
        jbtnCrop.setPreferredSize(new java.awt.Dimension(30, 30));
        jbtnCrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCropActionPerformed(evt);
            }
        });

        toolBar.add(jbtnCrop);

        jPanel3.setMaximumSize(new java.awt.Dimension(15, 32767));
        jPanel3.setOpaque(false);
        toolBar.add(jPanel3);

        jLabel2.setText("Foco:");
        jLabel2.setMaximumSize(null);
        jLabel2.setMinimumSize(null);
        jLabel2.setPreferredSize(null);
        toolBar.add(jLabel2);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 4, 5));

        jPanel4.setMaximumSize(new java.awt.Dimension(15, 32767));
        jPanel4.setMinimumSize(new java.awt.Dimension(3, 10));
        jPanel4.setOpaque(false);
        jPanel4.setPreferredSize(new java.awt.Dimension(4, 10));
        toolBar.add(jPanel4);

        jPanelFoco.setMaximumSize(new java.awt.Dimension(130, 32767));
        jPanelFoco.setMinimumSize(new java.awt.Dimension(120, 25));
        jPanelFoco.setPreferredSize(new java.awt.Dimension(130, 33));
        jSliderBlurSharp.setMajorTickSpacing(30);
        jSliderBlurSharp.setMaximum(300);
        jSliderBlurSharp.setMinorTickSpacing(30);
        jSliderBlurSharp.setSnapToTicks(true);
        jSliderBlurSharp.setToolTipText("Desfocar / Agu\u00e7ar");
        jSliderBlurSharp.setValue(150);
        jSliderBlurSharp.setMaximumSize(new java.awt.Dimension(100, 24));
        jSliderBlurSharp.setPreferredSize(new java.awt.Dimension(120, 24));
        jSliderBlurSharp.setValueIsAdjusting(true);
        jSliderBlurSharp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderBlurSharpStateChanged(evt);
            }
        });

        jPanelFoco.add(jSliderBlurSharp);

        toolBar.add(jPanelFoco);

        jPanel6.setMaximumSize(new java.awt.Dimension(15, 32767));
        jPanel6.setOpaque(false);
        jPanel6.setPreferredSize(new java.awt.Dimension(15, 10));
        toolBar.add(jPanel6);

        jLabel3.setText("Detec\u00e7\u00e3o de bordas:");
        jLabel3.setMaximumSize(null);
        jLabel3.setMinimumSize(null);
        jLabel3.setPreferredSize(null);
        toolBar.add(jLabel3);

        jPanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 4, 5));

        jPanel10.setMaximumSize(new java.awt.Dimension(15, 32767));
        jPanel10.setOpaque(false);
        jPanel10.setPreferredSize(new java.awt.Dimension(6, 10));
        toolBar.add(jPanel10);

        jPanelGradient.setMaximumSize(new java.awt.Dimension(110, 32767));
        jPanelGradient.setMinimumSize(new java.awt.Dimension(95, 25));
        jPanelGradient.setPreferredSize(null);
        for (int i = 0; i < FerramentasImagem.kernelLabels.length; i++) {
            kernelBox.addItem(FerramentasImagem.kernelLabels[i]);
        }
        kernelBox.setToolTipText("Detectar bordas");
        kernelBox.setMaximumSize(new java.awt.Dimension(100, 32767));
        kernelBox.setMinimumSize(new java.awt.Dimension(50, 20));
        kernelBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kernelBoxActionPerformed(evt);
            }
        });

        jPanelGradient.add(kernelBox);

        toolBar.add(jPanelGradient);

        jPanel9.setMaximumSize(new java.awt.Dimension(15, 32767));
        jPanel9.setOpaque(false);
        toolBar.add(jPanel9);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jbtnOkImage.setText("Ok");
        jbtnOkImage.setToolTipText("Salva as altera\u00e7\u00f5es");
        jbtnOkImage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnOkImage.setMaximumSize(new java.awt.Dimension(60, 23));
        jbtnOkImage.setMinimumSize(new java.awt.Dimension(47, 23));
        jbtnOkImage.setPreferredSize(new java.awt.Dimension(60, 23));
        jbtnOkImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOkImageActionPerformed(evt);
            }
        });

        jPanel8.add(jbtnOkImage);

        jbtnCancel.setText("Cancelar");
        jbtnCancel.setToolTipText("Cancela as altera\u00e7\u00f5es");
        jbtnCancel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnCancel.setMaximumSize(new java.awt.Dimension(60, 23));
        jbtnCancel.setMinimumSize(new java.awt.Dimension(47, 23));
        jbtnCancel.setPreferredSize(new java.awt.Dimension(60, 23));
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        jPanel8.add(jbtnCancel);

        toolBar.add(jPanel8);

        add(toolBar, java.awt.BorderLayout.NORTH);

    }
    // </editor-fold>//GEN-END:initComponents

    private void jbtnCropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCropActionPerformed
    	jbtnOkImage.setEnabled(false);
    	if( sapo.numImg > 0 ) sapo.frmImagem.crop();
    }//GEN-LAST:event_jbtnCropActionPerformed

    private void jbtnContrDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnContrDownActionPerformed
    	if( sapo.numImg > 0 ) sapo.frmImagem.contrasteDown();
    }//GEN-LAST:event_jbtnContrDownActionPerformed

    private void jbtnContrUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnContrUpActionPerformed
    	if( sapo.numImg > 0 ) sapo.frmImagem.contrasteUp();
    }//GEN-LAST:event_jbtnContrUpActionPerformed

    private void jbtnFlipVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFlipVActionPerformed
        if( sapo.numImg > 0 ) sapo.frmImagem.transposeImg(FLIP_VERTICAL);
    }//GEN-LAST:event_jbtnFlipVActionPerformed

    private void jbtnFlipHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFlipHActionPerformed
        if( sapo.numImg > 0 ) sapo.frmImagem.transposeImg(FLIP_HORIZONTAL); 
    }//GEN-LAST:event_jbtnFlipHActionPerformed

    private void jbtnRot270ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRot270ActionPerformed
        if( sapo.numImg > 0 ) sapo.frmImagem.transposeImg(ROTATE_270);
    }//GEN-LAST:event_jbtnRot270ActionPerformed

    private void jbtnRot90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRot90ActionPerformed
        if( sapo.numImg > 0 ) sapo.frmImagem.transposeImg(ROTATE_90);
    }//GEN-LAST:event_jbtnRot90ActionPerformed

    private void jbtnSolDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSolDownActionPerformed
        if( sapo.numImg > 0 ) sapo.frmImagem.brilhoDown();
    }//GEN-LAST:event_jbtnSolDownActionPerformed

    private void jbtnSolUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSolUpActionPerformed
        if( sapo.numImg > 0 ) sapo.frmImagem.brilhoUp();
    }//GEN-LAST:event_jbtnSolUpActionPerformed

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
    	doCancel();
    }//GEN-LAST:event_jbtnCancelActionPerformed

    public void doCancel() {
    	setEnabledAll(true);
    	sapo.jif[sapo.numImg].setRenderedImage(sapo.frmImagem.pimg);
    	sapo.showInternalFrameWithImage(sapo.numImg);
    	sapo.frmImagem.inicializaParametros();
    	if (sapo.frmImagem.cropDialog != null) {
    		sapo.frmImagem.cropDialog.setVisible(false);
    		sapo.frmImagem.cropDialog.dispose();
    		sapo.frmImagem.desacoplar(sapo.numImg);
    	}
	}

	private void kernelBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kernelBoxActionPerformed
    	if( sapo.numImg > 0 ) {
    		int i = kernelBox.getSelectedIndex();
    		// Set the appropriate kernel and do Gradient
    		int tmp = i * 2;
    		sapo.frmImagem.initKernels();
    		sapo.frmImagem.kern_h = sapo.frmImagem.kernels[tmp];
    		sapo.frmImagem.kern_v = sapo.frmImagem.kernels[tmp+1];
    		sapo.frmImagem.gradient();
    	}
    }//GEN-LAST:event_kernelBoxActionPerformed

    private void jSliderBlurSharpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderBlurSharpStateChanged
    	if ((sapo.numImg > 0) && (jSliderBlurSharp.getValue()%30 == 0)) 
    		sapo.frmImagem.blurSharp(jSliderBlurSharp.getValue());
    }//GEN-LAST:event_jSliderBlurSharpStateChanged

    private void jbtnOkImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOkImageActionPerformed
    	doOk();
    }//GEN-LAST:event_jbtnOkImageActionPerformed
    
    
    public void doOk() {
    	boolean mudaImagem = true;
    	if (sapo.frmImagem.op.equals("crop") && (sapo.frmImagem.cropDialog != null)) {
    		sapo.frmImagem.cropDialog.setVisible(false);
    		sapo.frmImagem.cropDialog.dispose();
    		sapo.frmImagem.desacoplar(sapo.numImg);
    	}
    	if (sapo.frmImagem.op.equals("crop") || sapo.frmImagem.op.equals("transpose"))
    		mudaImagem = confirmaAlteracao();
    	if (mudaImagem && (sapo.numImg > 0)) {
			sapo.frmImagem.pimg=sapo.jif[sapo.numImg].getRenderedImage();
			sapo.frmImagem.editou = false;
			sapo.saveImage(sapo.jif[sapo.numImg].file.getPath());
			//sapo.desejaSalvarImagem();
		}
    	else {
    		sapo.jif[sapo.numImg].setRenderedImage(sapo.frmImagem.pimg);
    		sapo.showInternalFrameWithImage(sapo.numImg);
    	}
		setEnabledAll(true);
		jbtnOkImage.setEnabled(true);
		sapo.frmImagem.inicializaParametros();
	}

	private boolean confirmaAlteracao() {
		boolean retorno = true;
		if ((sapo.numImg > 0) && (!sapo.paciente.dados.imgData[sapo.numImg].pontosList.isEmpty())) {
			Object[] options = {"Sim","Não"};
			int result = JOptionPane.showOptionDialog(sapo,
					"Esta imagem foi contém pontos previamente marcados!\n" +
					"Esta operação irá apagar todos os pontos marcados.\n" +
					"Deseja confirmar a alteração na imagem?  ",
					"Aviso",JOptionPane.YES_NO_OPTION,
					JOptionPane.QUESTION_MESSAGE,
					null, options, options[0]);
			if (result == JOptionPane.NO_OPTION) retorno = false;
			else sapo.paciente.dados.imgData[sapo.numImg].pontosList.clear();
		}
		return retorno;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupImagem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelFoco;
    private javax.swing.JPanel jPanelGradient;
    private javax.swing.JSlider jSliderBlurSharp;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnContrDown;
    private javax.swing.JButton jbtnContrUp;
    private javax.swing.JButton jbtnCrop;
    private javax.swing.JButton jbtnFlipH;
    private javax.swing.JButton jbtnFlipV;
    private javax.swing.JButton jbtnOkImage;
    private javax.swing.JButton jbtnRot270;
    private javax.swing.JButton jbtnRot90;
    private javax.swing.JButton jbtnSolDown;
    private javax.swing.JButton jbtnSolUp;
    private javax.swing.JComboBox kernelBox;
    public javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
    
}
