import java.awt.Point;
import javax.swing.JOptionPane;
import com.dati.image.DistanciaMedida;
/*
 * MedeDistanciaPanel.java
 *
 * Created on 13 de Julho de 2005, 17:06
 */

/**
 *
 * @author  Anderson Zanardi de Freitas
 */
public class MedeDistanciaPanel extends javax.swing.JPanel {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 8598651926859845038L;
	SAPO sapo;
    int numImg;
    
    /** Creates new form MedeDistanciaPanel */
    public MedeDistanciaPanel(SAPO sapo) {
        this.sapo = sapo;
        initComponents();
        jTableMedeDist.getTableHeader().setReorderingAllowed(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jpopupMenuDist = new javax.swing.JPopupMenu();
        jMenu2 = new javax.swing.JMenu();
        jmenuItemOtimo1 = new javax.swing.JMenuItem();
        jmenuItem81 = new javax.swing.JMenuItem();
        jmenuItem101 = new javax.swing.JMenuItem();
        jmenuItem151 = new javax.swing.JMenuItem();
        jmtemZoom201 = new javax.swing.JMenuItem();
        jpMede = new javax.swing.JPanel();
        jPanelA = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanelB = new javax.swing.JPanel();
        jspMedeDist = new javax.swing.JScrollPane();
        jTableMedeDist = new javax.swing.JTable();
        jpnlMediDist = new javax.swing.JPanel();
        jLblMedeDist = new javax.swing.JLabel();
        jtxtMedeDist = new javax.swing.JTextField();
        jbtnInserirDist = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanelC = new javax.swing.JPanel();
        jbtnMedeDistOk = new javax.swing.JButton();
        jbtnMedeDistDeletar = new javax.swing.JButton();
        jbMedeDistClear = new javax.swing.JButton();
        jbMedeDistAjuda = new javax.swing.JButton();

        jMenu2.setText("Zoom");
        jMenu2.setToolTipText("Aplica zoom");
        jmenuItemOtimo1.setText("Ajusta");
        jmenuItemOtimo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuItemOtimo1ActionPerformed(evt);
            }
        });

        jMenu2.add(jmenuItemOtimo1);

        jmenuItem81.setText("80%");
        jmenuItem81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuItem81ActionPerformed(evt);
            }
        });

        jMenu2.add(jmenuItem81);

        jmenuItem101.setText("100%");
        jmenuItem101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuItem101ActionPerformed(evt);
            }
        });

        jMenu2.add(jmenuItem101);

        jmenuItem151.setText("150%");
        jmenuItem151.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuItem151ActionPerformed(evt);
            }
        });

        jMenu2.add(jmenuItem151);

        jmtemZoom201.setText("200%");
        jmtemZoom201.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmtemZoom201ActionPerformed(evt);
            }
        });

        jMenu2.add(jmtemZoom201);

        jpopupMenuDist.add(jMenu2);

        setLayout(new java.awt.BorderLayout());

        jpMede.setLayout(new java.awt.BorderLayout());

        jpMede.setMaximumSize(new java.awt.Dimension(2147483647, 250));
        jpMede.setMinimumSize(new java.awt.Dimension(11, 36));
        jPanelA.setLayout(new java.awt.GridBagLayout());

        jPanelA.setMinimumSize(new java.awt.Dimension(186, 35));
        jPanelA.setPreferredSize(new java.awt.Dimension(186, 35));
        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12));
        jLabel6.setText("Medidas de dist\u00e2ncia");
        jPanelA.add(jLabel6, new java.awt.GridBagConstraints());

        jpMede.add(jPanelA, java.awt.BorderLayout.NORTH);

        jPanelB.setLayout(new java.awt.BorderLayout());

        jspMedeDist.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jspMedeDist.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jspMedeDist.setMaximumSize(new java.awt.Dimension(300, 70));
        jspMedeDist.setMinimumSize(new java.awt.Dimension(250, 70));
        jspMedeDist.setPreferredSize(new java.awt.Dimension(250, 200));
        jspMedeDist.setRequestFocusEnabled(false);
        jTableMedeDist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medida", "X", "Apresenta"
            }
        ) {
            /**
			 * 
			 */
			private static final long serialVersionUID = -6256554352633455930L;
			Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableMedeDist.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableMedeDistPropertyChange(evt);
            }
        });

        jspMedeDist.setViewportView(jTableMedeDist);

        jPanelB.add(jspMedeDist, java.awt.BorderLayout.CENTER);

        jLblMedeDist.setText("Dist\u00e2ncia");
        jpnlMediDist.add(jLblMedeDist);

        jtxtMedeDist.setColumns(6);
        jtxtMedeDist.setEditable(false);
        jtxtMedeDist.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jpnlMediDist.add(jtxtMedeDist);

        jbtnInserirDist.setText("Inserir");
        jbtnInserirDist.setToolTipText("Insere a medida na tabela");
        jbtnInserirDist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInserirDistActionPerformed(evt);
            }
        });

        jpnlMediDist.add(jbtnInserirDist);

        jpnlMediDist.add(jPanel1);

        jPanelB.add(jpnlMediDist, java.awt.BorderLayout.NORTH);

        jpMede.add(jPanelB, java.awt.BorderLayout.CENTER);

        jPanelC.setMinimumSize(new java.awt.Dimension(288, 40));
        jPanelC.setPreferredSize(new java.awt.Dimension(288, 35));
        jbtnMedeDistOk.setText("OK");
        jbtnMedeDistOk.setToolTipText("Escreve pontos na base de dados do projeto e encerra esta opera\u00e7\u00e3o");
        jbtnMedeDistOk.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnMedeDistOk.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jbtnMedeDistOk.setMaximumSize(new java.awt.Dimension(9999, 9999));
        jbtnMedeDistOk.setMinimumSize(new java.awt.Dimension(72, 25));
        jbtnMedeDistOk.setPreferredSize(new java.awt.Dimension(50, 25));
        jbtnMedeDistOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMedeDistOkActionPerformed(evt);
            }
        });

        jPanelC.add(jbtnMedeDistOk);

        jbtnMedeDistDeletar.setText("Apagar");
        jbtnMedeDistDeletar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnMedeDistDeletar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jbtnMedeDistDeletar.setMaximumSize(new java.awt.Dimension(9999, 9999));
        jbtnMedeDistDeletar.setMinimumSize(new java.awt.Dimension(72, 25));
        jbtnMedeDistDeletar.setPreferredSize(new java.awt.Dimension(50, 25));
        jbtnMedeDistDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMedeDistDeletarActionPerformed(evt);
            }
        });

        jPanelC.add(jbtnMedeDistDeletar);

        jbMedeDistClear.setText("Limpar");
        jbMedeDistClear.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbMedeDistClear.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jbMedeDistClear.setMaximumSize(new java.awt.Dimension(9999, 9999));
        jbMedeDistClear.setMinimumSize(new java.awt.Dimension(72, 25));
        jbMedeDistClear.setPreferredSize(new java.awt.Dimension(50, 25));
        jbMedeDistClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMedeDistClearActionPerformed(evt);
            }
        });

        jPanelC.add(jbMedeDistClear);

        jbMedeDistAjuda.setText("Ajuda");
        jbMedeDistAjuda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbMedeDistAjuda.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jbMedeDistAjuda.setMaximumSize(new java.awt.Dimension(9999, 9999));
        jbMedeDistAjuda.setMinimumSize(new java.awt.Dimension(72, 25));
        jbMedeDistAjuda.setPreferredSize(new java.awt.Dimension(50, 25));
        jbMedeDistAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMedeDistAjudaActionPerformed(evt);
            }
        });

        jPanelC.add(jbMedeDistAjuda);

        jpMede.add(jPanelC, java.awt.BorderLayout.SOUTH);

        add(jpMede, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents

    private void jbMedeDistAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMedeDistAjudaActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jbMedeDistAjudaActionPerformed

    private void jmenuItemOtimo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuItemOtimo1ActionPerformed
        sapo.restauraZoom();
        sapo.mostraZoom(sapo.jpMedeDist, "MedeDistancia");
    }//GEN-LAST:event_jmenuItemOtimo1ActionPerformed

    private void jmenuItem81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuItem81ActionPerformed
        sapo.jif[sapo.numImg].zoom = 80;
        if (sapo.jif[sapo.numImg].flagImg)
            sapo.showInternalFrameWithImage(sapo.numImg);
        sapo.mostraZoom(sapo.jpMedeDist, "MedeDistancia");
    }//GEN-LAST:event_jmenuItem81ActionPerformed

    private void jmenuItem101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuItem101ActionPerformed
        sapo.jif[sapo.numImg].zoom = 100;
        if (sapo.jif[sapo.numImg].flagImg)
            sapo.showInternalFrameWithImage(sapo.numImg);
        sapo.mostraZoom(sapo.jpMedeDist, "MedeDistancia");
    }//GEN-LAST:event_jmenuItem101ActionPerformed

    private void jmenuItem151ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuItem151ActionPerformed
        sapo.jif[sapo.numImg].zoom = 150;
        if (sapo.jif[sapo.numImg].flagImg)
            sapo.showInternalFrameWithImage(sapo.numImg);
        sapo.mostraZoom(sapo.jpMedeDist, "MedeDistancia");
    }//GEN-LAST:event_jmenuItem151ActionPerformed

    private void jmtemZoom201ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmtemZoom201ActionPerformed
        sapo.jif[sapo.numImg].zoom = 200;
        if (sapo.jif[sapo.numImg].flagImg)
            sapo.showInternalFrameWithImage(sapo.numImg);
        sapo.mostraZoom(sapo.jpMedeDist, "MedeDistancia");
    }//GEN-LAST:event_jmtemZoom201ActionPerformed

    private void jTableMedeDistPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableMedeDistPropertyChange
    	if ((sapo.numImg > 0) && (sapo.jif[sapo.numImg] != null) && sapo.jif[sapo.numImg].flagImg) {
    		atualizaPropriedadesMedida();
    		atualizar();
    		sapo.jif[sapo.numImg].jaiP.setEspLinhaCorLinha(sapo.corDesenho, sapo.espLinha);
    	}
    }//GEN-LAST:event_jTableMedeDistPropertyChange

    public void atualizaPropriedadesMedida() {
    	if ((sapo.numImg > 0) && (sapo.jif[sapo.numImg] != null) && sapo.jif[sapo.numImg].flagImg) {
    		int numLinha = jTableMedeDist.getEditingRow();
    		boolean numPontos = sapo.paciente.dados.imgData[sapo.numImg].distanciaList.isEmpty();
    		if ((numLinha >= 0)&&(!numPontos)) {
    			sapo.jif[sapo.numImg].jaiP.resetMousePosition();
    			String labelDist = String.valueOf(jTableMedeDist.getValueAt(numLinha,0)); //nome das colunas
    			sapo.paciente.dados.imgData[sapo.numImg].setMedetLabel(labelDist, numLinha);
    			boolean apresentaTemp = ((Boolean)jTableMedeDist.getValueAt(numLinha,2)).booleanValue();
    			sapo.paciente.dados.imgData[sapo.numImg].setMedeApresenta(apresentaTemp, numLinha);//addPoint(x, y, labelPonto, apresentaTemp);
    		}
    		sapo.jif[sapo.numImg].flagPontos = true;
    	}
    }
    
    private void jbtnMedeDistOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMedeDistOkActionPerformed
        sapo.restauraZoom();
        aplica();
        sapo.paciente.escreveDB();
        sapo.paciente.salvarAlteracoes = false;
        sapo.restauraInternalFrameOriginal();
    }//GEN-LAST:event_jbtnMedeDistOkActionPerformed

    private void jbtnMedeDistDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMedeDistDeletarActionPerformed
        apagar();
    }//GEN-LAST:event_jbtnMedeDistDeletarActionPerformed

    private void jbtnInserirDistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInserirDistActionPerformed
        inserir();
    }//GEN-LAST:event_jbtnInserirDistActionPerformed

    private void jbMedeDistClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMedeDistClearActionPerformed
        this.numImg = sapo.numImg;
        int result = JOptionPane.showConfirmDialog (sapo,
                "Apagar TODAS as distâncias\n" +
                "medidas para esta imagem ?\n" +
                "(esta ação não pode ser desfeita)\n",
                "Confirmação", JOptionPane.YES_NO_OPTION);
        if( result == JOptionPane.YES_OPTION) {
             limpaTabela();
             sapo.paciente.dados.imgData[sapo.numImg].limpaDistanciaMedida(); 
             sapo.jif[numImg].jaiP.limpaListaDistancia();
        }
    }//GEN-LAST:event_jbMedeDistClearActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLblMedeDist;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelA;
    private javax.swing.JPanel jPanelB;
    private javax.swing.JPanel jPanelC;
    public javax.swing.JTable jTableMedeDist;
    private javax.swing.JButton jbMedeDistAjuda;
    private javax.swing.JButton jbMedeDistClear;
    private javax.swing.JButton jbtnInserirDist;
    private javax.swing.JButton jbtnMedeDistDeletar;
    private javax.swing.JButton jbtnMedeDistOk;
    private javax.swing.JMenuItem jmenuItem101;
    private javax.swing.JMenuItem jmenuItem151;
    private javax.swing.JMenuItem jmenuItem81;
    private javax.swing.JMenuItem jmenuItemOtimo1;
    private javax.swing.JMenuItem jmtemZoom201;
    private javax.swing.JPanel jpMede;
    private javax.swing.JPanel jpnlMediDist;
    public javax.swing.JPopupMenu jpopupMenuDist;
    private javax.swing.JScrollPane jspMedeDist;
    public javax.swing.JTextField jtxtMedeDist;
    // End of variables declaration//GEN-END:variables

   
    public void atualizar() {
    	if ((sapo.numImg > 0) && (sapo.jif[sapo.numImg] != null) && sapo.jif[sapo.numImg].flagImg) {
    		numImg = sapo.numImg;
    		float zoom = sapo.jif[sapo.numImg].zoom / 100.0F;
    		sapo.jif[sapo.numImg].jaiP.setZoom(zoom);
    		limpaTabela();
    		javax.swing.table.DefaultTableModel a = (javax.swing.table.DefaultTableModel)jTableMedeDist.getModel();
    		java.util.ArrayList valores = sapo.paciente.dados.imgData[numImg].getDistanciaMedida();   
    		try {
    			repaint();
    			for (int i=0; i<valores.size(); i++){
    				a.insertRow(i, new Object[]{null});
    				String nomeTemp = ((DistanciaMedida)valores.get(i)).nome;
    				double distanciaTemp = ((DistanciaMedida)valores.get(i)).distanciaMedida;
    				boolean bl = ((DistanciaMedida)valores.get(i)).apresentaDist;
    				jTableMedeDist.setValueAt(nomeTemp, i, 0);
    				jTableMedeDist.setValueAt(new Double(distanciaTemp), i, 1);
    				jTableMedeDist.setValueAt(new Boolean(bl), i, 2);
    				sapo.jif[numImg].jaiP.atualizaApresentaDistancia(valores);
    			}
    			sapo.jif[numImg].jaiP.setPaint(false, false, false, false);
    		} catch (Exception e) {
    			sapo.errorReport.jtxtErrorReport.append(e.toString()+"\n");
    			e.printStackTrace();
    			sapo.error = e.getStackTrace();
    			for(int k=0; k< sapo.error.length; k++)
    				sapo.errorReport.jtxtErrorReport.append(sapo.error[k].toString()+"\n");
    			sapo.errorReport.jtxtErrorReport.append("==========================================="+"\n");
    			sapo.jdlgErrorReport.pack();
    			sapo.jdlgErrorReport.setVisible(true);
    		}
    	}
    }
    
    private void aplica() {
        this.numImg = sapo.numImg;
        javax.swing.table.DefaultTableModel a = (javax.swing.table.DefaultTableModel)jTableMedeDist.getModel();
        int numLinhas = a.getRowCount();
        repaint();
        if(numLinhas>0)
        for(int i=0; i<numLinhas; i++){
            String labelDist = String.valueOf(jTableMedeDist.getValueAt(i,0)); //nome das colunas
            boolean bl = ((Boolean)jTableMedeDist.getValueAt(i,2)).booleanValue();
            sapo.paciente.dados.imgData[numImg].atualizaDistanciaMedida(labelDist, bl, i);
        }
    }
    
    public void limpaTabela() {
        this.numImg = sapo.numImg;
        javax.swing.table.DefaultTableModel a = (javax.swing.table.DefaultTableModel)jTableMedeDist.getModel();
        int numLinha = a.getRowCount(); 
        if (numLinha>0)
            for (int i=(numLinha-1); i>=0; i--){
                a.removeRow(i);
            }
        jtxtMedeDist.setText("");
        sapo.jif[numImg].jaiP.resetMousePosition();
        sapo.jif[numImg].jaiP.repaint();
    }
    
    private void apagar() {
        this.numImg = sapo.numImg;
        
        javax.swing.table.DefaultTableModel a = (javax.swing.table.DefaultTableModel)jTableMedeDist.getModel();
        try{
           // int index = jTableMedeDist.getSelectedRow();
           // a.removeRow(index);
            int indexs[] = jTableMedeDist.getSelectedRows();
            for(int i=(indexs.length-1); i>=0; i--){
                a.removeRow(indexs[i]);
                sapo.paciente.dados.imgData[sapo.numImg].removeDistanciaMedida(indexs[i]);
                sapo.jif[numImg].jaiP.removeDistancia(indexs[i]);
            }
          //  sapo.paciente.dados.imgData[sapo.numImg].removeDistanciaMedida(index);
          //  sapo.jif[numImg].jaiP.removeDistancia(index);
        } catch(ArrayIndexOutOfBoundsException e){JOptionPane.showMessageDialog(sapo,"Nenhuma linha foi selecionada na tabela");};
        sapo.jif[numImg].jaiP.setPaint(false, false, false, false);
    }
    
    private void inserir() {
        if( jtxtMedeDist.getText().length() == 0){
            JOptionPane.showMessageDialog(sapo,
                "Verifique sua digitação. \nFormato correto: \"XX,XX\" ",
                "Formato atual é inválido", JOptionPane.PLAIN_MESSAGE);
            return;
        }  
        else{
            this.numImg = sapo.numImg;
            Point[] ptMedidas = sapo.jif[numImg].jaiP.getptDistancia();
            double distanciaMedida = sapo.doubleLoc(jtxtMedeDist.getText());
            jtxtMedeDist.setText("");
            javax.swing.table.DefaultTableModel a = (javax.swing.table.DefaultTableModel)jTableMedeDist.getModel();
            int numLinha = a.getRowCount(); 
            a.insertRow(numLinha, new Object[]{null});
            jTableMedeDist.setValueAt("Distância "+numLinha, numLinha, 0);
            jTableMedeDist.setValueAt(new Double(distanciaMedida), numLinha, 1);
            jTableMedeDist.setValueAt(new Boolean(true), numLinha, 2);
            String nome = String.valueOf(a.getValueAt(numLinha,0));
            sapo.paciente.dados.imgData[numImg].addDistanciaMedida(ptMedidas,nome,distanciaMedida,true);
            sapo.jif[numImg].jaiP.addDistancia(ptMedidas, true);
            sapo.paciente.salvarAlteracoes = true;
        }
    } //inserir
}
