import java.awt.BorderLayout;
import java.net.URL;

import javax.swing.JEditorPane;
import javax.swing.JScrollPane;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;

import com.dati.gui.EscapeDialog;
import com.dati.net.BrowserControl;

/*
 * Sobre.java
 *
 * Created on 7 de Fevereiro de 2005, 17:01
 */

/**
 *
 * @author  TOSHIBA
 */
public class Sobre extends javax.swing.JPanel implements HyperlinkListener {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 6747644701792043185L;
	private SAPO sapo;
        private JEditorPane htmlPane = null;
    EscapeDialog jDialogAbertura;
    
    /** Creates new form Sobre */
    public Sobre(SAPO sapo) {
        this.sapo = sapo;
        initComponents();
        initEditorPane();
        setEditorPaneContent(sapo.getClass().getResource("/res/sobre.html"));
        JScrollPane scrollPane = new JScrollPane(htmlPane);
        jPanelMsg.add(scrollPane,BorderLayout.CENTER);
        jlbl2Sobre.setForeground(java.awt.SystemColor.activeCaptionText);
        htmlPane.setVisible(true);
    }
    
    private void initEditorPane() {
    	htmlPane = new JEditorPane();
        htmlPane.setEditable(false);
        htmlPane.setContentType("text/html");
        htmlPane.addHyperlinkListener(this);
    }
    
    private void setEditorPaneContent(URL url) {
        try {
            htmlPane.setPage(url);
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Erro : não consegui abrir arquivo " + url.getPath());
        }
    }
    
    public void hyperlinkUpdate(HyperlinkEvent evt) {
        if (evt.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
            URL url = null;
            String strURL = null;
            try {
                url = evt.getURL();
                strURL = url.toString();
                BrowserControl.displayURL(strURL);
            } catch (Exception e) {
                e.printStackTrace();
                System.out.println("Erro : não consegui abrir o arquivo " + strURL);
            }
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelSouth = new javax.swing.JPanel();
        jbtnOkSobre = new javax.swing.JButton();
        jbtnSobreLicenca = new javax.swing.JButton();
        jbtnOkSobre2 = new javax.swing.JButton();
        jPanelMain = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jlbl2Sobre = new SmoothLabel();
        jlbl2Sobre1 = new SmoothLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new SmoothLabel();
        jLabel16 = new SmoothLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelMsg = new javax.swing.JPanel();
        jPanelMsg2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        setMinimumSize(new java.awt.Dimension(631, 450));
        setPreferredSize(new java.awt.Dimension(631, 450));
        jPanelSouth.setLayout(new java.awt.GridLayout(1, 0));

        jPanelSouth.setPreferredSize(new java.awt.Dimension(345, 35));
        jbtnOkSobre.setFont(new java.awt.Font("SansSerif", 0, 12));
        jbtnOkSobre.setText("O K");
        jbtnOkSobre.setFocusable(false);
        jbtnOkSobre.setMaximumSize(new java.awt.Dimension(55, 28));
        jbtnOkSobre.setMinimumSize(new java.awt.Dimension(55, 28));
        jbtnOkSobre.setPreferredSize(new java.awt.Dimension(55, 28));
        jbtnOkSobre.setRequestFocusEnabled(false);
        jbtnOkSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOkSobreActionPerformed(evt);
            }
        });

        jPanelSouth.add(jbtnOkSobre);

        jbtnSobreLicenca.setFont(new java.awt.Font("SansSerif", 0, 12));
        jbtnSobreLicenca.setText("Licen\u00e7a");
        jbtnSobreLicenca.setFocusable(false);
        jbtnSobreLicenca.setMaximumSize(new java.awt.Dimension(55, 28));
        jbtnSobreLicenca.setMinimumSize(new java.awt.Dimension(55, 28));
        jbtnSobreLicenca.setPreferredSize(new java.awt.Dimension(55, 28));
        jbtnSobreLicenca.setRequestFocusEnabled(false);
        jbtnSobreLicenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSobreLicencaActionPerformed(evt);
            }
        });

        jPanelSouth.add(jbtnSobreLicenca);

        jbtnOkSobre2.setFont(new java.awt.Font("SansSerif", 0, 12));
        jbtnOkSobre2.setText("Tela de Abertura");
        jbtnOkSobre2.setFocusable(false);
        jbtnOkSobre2.setMaximumSize(new java.awt.Dimension(55, 28));
        jbtnOkSobre2.setMinimumSize(new java.awt.Dimension(55, 28));
        jbtnOkSobre2.setPreferredSize(new java.awt.Dimension(55, 28));
        jbtnOkSobre2.setRequestFocusEnabled(false);
        jbtnOkSobre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOkSobre2ActionPerformed(evt);
            }
        });

        jPanelSouth.add(jbtnOkSobre2);

        add(jPanelSouth, java.awt.BorderLayout.SOUTH);

        jPanelMain.setLayout(new java.awt.BorderLayout());

        jPanelMain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelMain.setMinimumSize(new java.awt.Dimension(412, 105));
        jPanelMain.setPreferredSize(new java.awt.Dimension(304, 164));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 80));
        jPanel10.setLayout(new java.awt.GridBagLayout());

        jPanel10.setPreferredSize(new java.awt.Dimension(410, 36));
        jlbl2Sobre.setBackground(new java.awt.Color(255, 255, 255));
        jlbl2Sobre.setFont(new java.awt.Font("Verdana", 1, 26));
        jlbl2Sobre.setForeground(new java.awt.Color(251, 252, 237));
        jlbl2Sobre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl2Sobre.setText("Software para Avalia\u00e7\u00e3o Postural - SAPO");
        jlbl2Sobre.setFocusable(false);
        jlbl2Sobre.setMaximumSize(new java.awt.Dimension(650, 35));
        jlbl2Sobre.setMinimumSize(new java.awt.Dimension(610, 35));
        jlbl2Sobre.setPreferredSize(new java.awt.Dimension(600, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 6;
        jPanel10.add(jlbl2Sobre, gridBagConstraints);

        jlbl2Sobre1.setBackground(new java.awt.Color(255, 255, 255));
        jlbl2Sobre1.setFont(new java.awt.Font("Verdana", 1, 26));
        jlbl2Sobre1.setForeground(javax.swing.UIManager.getDefaults().getColor("controlShadow"));
        jlbl2Sobre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl2Sobre1.setText("Software para Avalia\u00e7\u00e3o Postural - SAPO");
        jlbl2Sobre1.setFocusable(false);
        jlbl2Sobre1.setMaximumSize(new java.awt.Dimension(650, 35));
        jlbl2Sobre1.setMinimumSize(new java.awt.Dimension(610, 35));
        jlbl2Sobre1.setPreferredSize(new java.awt.Dimension(600, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 0, 0);
        jPanel10.add(jlbl2Sobre1, gridBagConstraints);

        jPanel1.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel9.setLayout(new java.awt.GridBagLayout());

        jPanel9.setMinimumSize(new java.awt.Dimension(10, 26));
        jPanel9.setPreferredSize(new java.awt.Dimension(10, 26));
        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14));
        jLabel15.setForeground(java.awt.SystemColor.activeCaptionText);
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("versão "+SAPO.VERSION+" - "+SAPO.RELEASEDATE);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel9.add(jLabel15, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14));
        jLabel16.setForeground(java.awt.SystemColor.controlShadow);
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("versão "+SAPO.VERSION+" - "+SAPO.RELEASEDATE);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanel9.add(jLabel16, gridBagConstraints);

        jPanel1.add(jPanel9, java.awt.BorderLayout.SOUTH);

        jPanelMain.add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanelMsg.setLayout(new java.awt.BorderLayout());

        jPanel2.add(jPanelMsg, java.awt.BorderLayout.CENTER);

        jPanelMsg2.setLayout(new java.awt.GridBagLayout());

        jPanelMsg2.setPreferredSize(new java.awt.Dimension(279, 30));
        jPanel2.add(jPanelMsg2, java.awt.BorderLayout.SOUTH);

        jPanel4.setPreferredSize(new java.awt.Dimension(50, 10));
        jPanel2.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel5.setPreferredSize(new java.awt.Dimension(50, 10));
        jPanel2.add(jPanel5, java.awt.BorderLayout.EAST);

        jPanel6.setPreferredSize(new java.awt.Dimension(10, 20));
        jPanel2.add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanelMain.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanelMain, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents

    private void jbtnOkSobre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOkSobre2ActionPerformed
        jDialogAbertura = new EscapeDialog(sapo);
        jDialogAbertura.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialogAbertura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jDialogAbertura.setFocusCycleRoot(false);
        jDialogAbertura.setFocusable(false);
        jDialogAbertura.setFocusableWindowState(false);
        jDialogAbertura.setFont(getFont());
        jDialogAbertura.setModal(true);
        jDialogAbertura.setName("Abertura");
        jDialogAbertura.setResizable(false);
        jDialogAbertura.setUndecorated(true);
        jDialogAbertura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDialogAbertura.setVisible(false);
            }
        });
        jDialogAbertura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDialogAbertura.setVisible(false);
            }
        });
        javax.swing.JLabel jlblAbertura = new javax.swing.JLabel();
        jlblAbertura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/splash.jpg")));
        jlblAbertura.setFocusable(false);
        jlblAbertura.setIconTextGap(0);
        jDialogAbertura.getContentPane().add(jlblAbertura);
        jDialogAbertura.pack();
        SAPO.center(jDialogAbertura);
        jDialogAbertura.setVisible(true);
    }//GEN-LAST:event_jbtnOkSobre2ActionPerformed

    private void jbtnSobreLicencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSobreLicencaActionPerformed
    	if (jbtnSobreLicenca.getText().equals("Licen\u00e7a")) {
    		setEditorPaneContent(sapo.getClass().getResource("/res/licenca.html"));
    		jbtnSobreLicenca.setText("Sobre");
    	}
    	else {
    		setEditorPaneContent(sapo.getClass().getResource("/res/sobre.html"));
    		jbtnSobreLicenca.setText("Licen\u00e7a");
    	}
    	this.repaint();
    }//GEN-LAST:event_jbtnSobreLicencaActionPerformed

    private void jbtnOkSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOkSobreActionPerformed
        sapo.jDialogSAPO.setVisible(false);
        sapo.jDialogSAPO.close();
    }//GEN-LAST:event_jbtnOkSobreActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelMsg;
    private javax.swing.JPanel jPanelMsg2;
    private javax.swing.JPanel jPanelSouth;
    private javax.swing.JButton jbtnOkSobre;
    private javax.swing.JButton jbtnOkSobre2;
    private javax.swing.JButton jbtnSobreLicenca;
    private javax.swing.JLabel jlbl2Sobre;
    private javax.swing.JLabel jlbl2Sobre1;
    // End of variables declaration//GEN-END:variables
    
}
