/*
 * UIUser.java
 *
 * Created on 30 de Janeiro de 2005, 21:55
 */

/**
 *
 * @author  Edison Puig Maldonado
 */

import com.sun.EFileFilter;
import com.tomtessier.scrollabledesktop.BaseInternalFrame;
import javax.swing.JFileChooser;

public class UIUser extends BaseInternalFrame {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = -931942361308277531L;
	public User user;
    public DadosUsuario dados;
    
    /** Creates new form UIUser */
    public UIUser() {
        super("SAPO - Usuário");
        initComponents();
        setVisible(true);
    }
    
    public UIUser(User user) {
        super("SAPO - Usuário");
        this.user = user;
        dados = user.dados;
        initComponents();
        setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jcbEstado = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbtnConfgOk = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jbtnConfgCancel = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("SAPO - Configura\u00e7\u00e3o do Usu\u00e1rio");
        setDesktopIcon(getDesktopIcon());
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("res/frog.gif")));
        try {
            setIcon(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setPreferredSize(new java.awt.Dimension(500, 410));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(115, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(470, 330));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel3.setMinimumSize(new java.awt.Dimension(335, 40));
        jPanel3.setPreferredSize(new java.awt.Dimension(335, 90));
        jLabel13.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Entre com os dados do respons\u00e1vel pelas an\u00e1lises");
        jPanel3.add(jLabel13, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jPanel3, gridBagConstraints);

        jLabel1.setText("Nome Completo :   ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel1, gridBagConstraints);

        jTextField1.setText(dados.nomecompleto);
        jTextField1.setMinimumSize(new java.awt.Dimension(300, 20));
        jTextField1.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanel1.add(jTextField1, gridBagConstraints);

        jLabel2.setText("Qualifica\u00e7\u00e3o :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel2, gridBagConstraints);

        jTextField2.setText(dados.qualificacao);
        jTextField2.setMinimumSize(new java.awt.Dimension(300, 20));
        jTextField2.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanel1.add(jTextField2, gridBagConstraints);

        jLabel3.setText("Associa\u00e7\u00e3o de classe :  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel3, gridBagConstraints);

        jTextField3.setText(dados.associacaoclasse);
        jTextField3.setMinimumSize(new java.awt.Dimension(300, 20));
        jTextField3.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        jPanel1.add(jTextField3, gridBagConstraints);

        jLabel4.setText("Institui\u00e7\u00e3o :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel4, gridBagConstraints);

        jTextField4.setText(dados.instituicao);
        jTextField4.setMinimumSize(new java.awt.Dimension(300, 20));
        jTextField4.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        jPanel1.add(jTextField4, gridBagConstraints);

        jLabel5.setText("Departamento :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel5, gridBagConstraints);

        jTextField5.setText(dados.depto);
        jTextField5.setMinimumSize(new java.awt.Dimension(300, 20));
        jTextField5.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 5;
        jPanel1.add(jTextField5, gridBagConstraints);

        jLabel6.setText("Logotipo :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel6, gridBagConstraints);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.X_AXIS));

        jTextField6.setText(dados.logotipo);
        jTextField6.setMinimumSize(new java.awt.Dimension(245, 20));
        jTextField6.setPreferredSize(new java.awt.Dimension(245, 20));
        jPanel8.add(jTextField6);

        jButton1.setText("Procurar");
        jButton1.setMargin(new java.awt.Insets(0, 4, 0, 4));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel8.add(jButton1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 6;
        jPanel1.add(jPanel8, gridBagConstraints);

        jLabel7.setText("Outros Dados :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel7, gridBagConstraints);

        jTextField7.setText(dados.outrosdados);
        jTextField7.setMinimumSize(new java.awt.Dimension(300, 20));
        jTextField7.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 7;
        jPanel1.add(jTextField7, gridBagConstraints);

        jLabel8.setText("Endere\u00e7o / CEP :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabel8, gridBagConstraints);

        jTextField8.setText(dados.enderecocep);
        jTextField8.setMinimumSize(new java.awt.Dimension(300, 20));
        jTextField8.setPreferredSize(new java.awt.Dimension(300, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 8;
        jPanel1.add(jTextField8, gridBagConstraints);

        jLabel18.setText("     Cidade : ");
        jPanel4.add(jLabel18);

        jTextField17.setText(dados.cidade);
        jTextField17.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextField17.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel4.add(jTextField17);

        jLabel19.setText(" Estado : ");
        jPanel4.add(jLabel19);

        jcbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "AC", "AL", "AP", "AM", "BA", "CE", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jcbEstado.setSelectedItem(dados.estado);
        jPanel4.add(jcbEstado);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jPanel4, gridBagConstraints);

        jLabel9.setText("Telefone : ");
        jPanel5.add(jLabel9);

        jTextField9.setText(dados.telefone);
        jTextField9.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextField9.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel5.add(jTextField9);

        jLabel10.setText("      Fax : ");
        jPanel5.add(jLabel10);

        jTextField10.setText(dados.fax);
        jTextField10.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextField10.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel5.add(jTextField10);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jPanel5, gridBagConstraints);

        jLabel11.setText("    E-mail  : ");
        jPanel6.add(jLabel11);

        jTextField11.setText(dados.email);
        jTextField11.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextField11.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel6.add(jTextField11);

        jLabel12.setText("      Site : ");
        jPanel6.add(jLabel12);

        jTextField12.setText(dados.site);
        jTextField12.setMinimumSize(new java.awt.Dimension(150, 20));
        jTextField12.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel6.add(jTextField12);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        jPanel1.add(jPanel6, gridBagConstraints);

        jPanel10.setMinimumSize(new java.awt.Dimension(10, 20));
        jPanel10.setPreferredSize(new java.awt.Dimension(10, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jPanel10, gridBagConstraints);

        jPanel7.add(jPanel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel2.setMinimumSize(new java.awt.Dimension(219, 40));
        jPanel2.setPreferredSize(new java.awt.Dimension(219, 35));
        jbtnConfgOk.setFont(new java.awt.Font("Tahoma", 0, 12));
        jbtnConfgOk.setText("Ok");
        jbtnConfgOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfgOkActionPerformed(evt);
            }
        });

        jPanel2.add(jbtnConfgOk);

        jButton7.setFont(new java.awt.Font("Tahoma", 0, 12));
        jButton7.setText("Aplicar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton7);

        jbtnConfgCancel.setFont(new java.awt.Font("Tahoma", 0, 12));
        jbtnConfgCancel.setText("Cancela");
        jbtnConfgCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConfgCancelActionPerformed(evt);
            }
        });

        jPanel2.add(jbtnConfgCancel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fc = new JFileChooser();
        String[] extensoes = new String[] {"gif", "jpg", "png", "tif", "bmp", "fpx", "pgm", "ppm"};
        EFileFilter filter = new EFileFilter(extensoes, "Arquivos de Imagens");
        fc.addChoosableFileFilter(filter);
        fc.setDialogTitle("SAPO - Configurar Logotipo");
        int returnVal = fc.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION)
            jTextField6.setText(fc.getSelectedFile().getPath());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbtnConfgCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConfgCancelActionPerformed
        dispose();
    }//GEN-LAST:event_jbtnConfgCancelActionPerformed

    private void jbtnConfgOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConfgOkActionPerformed
        setUserDados();
        user.escreveDB();
        dispose();
    }//GEN-LAST:event_jbtnConfgOkActionPerformed

    private void setUserDados() {
        dados.nomecompleto =  jTextField1.getText();
        dados.qualificacao =  jTextField2.getText();
        dados.associacaoclasse =  jTextField3.getText();
        dados.instituicao =  jTextField4.getText();
        dados.depto =  jTextField5.getText();
        dados.logotipo =  jTextField6.getText();
        dados.outrosdados =  jTextField7.getText();
        dados.enderecocep =  jTextField8.getText();
        dados.cidade = jTextField17.getText();
        dados.estado = (String)jcbEstado.getSelectedItem();
        dados.telefone =  jTextField9.getText();
        dados.fax =  jTextField10.getText();
        dados.email =  jTextField11.getText();
        dados.site =  jTextField12.getText();
    }
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        setUserDados();
        user.escreveDB();
    }//GEN-LAST:event_jButton7ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton jbtnConfgCancel;
    private javax.swing.JButton jbtnConfgOk;
    javax.swing.JComboBox jcbEstado;
    // End of variables declaration//GEN-END:variables
    
}
