import java.awt.BorderLayout;
import java.net.URL;

import javax.swing.JEditorPane;
import javax.swing.JScrollPane;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;

import com.dati.net.BrowserControl;
/*
 * Welcome.java
 *
 * Created on 7 de Fevereiro de 2005, 17:11
 */

/**
 *
 * @author Edison Puig Maldonado
 */

public class Welcome extends javax.swing.JPanel implements HyperlinkListener {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = -2065475685354336433L;
	private SAPO sapo;
    private JEditorPane htmlPane = null;
    
    /** Creates new form Welcome */
    public Welcome(SAPO sapo) {
        this.sapo = sapo;
        initComponents();
        initEditorPane();
        setEditorPaneContent(sapo.getClass().getResource("/res/welcome.html"));
        JScrollPane scrollPane = new JScrollPane(htmlPane);
        jPanelWelcome1.add(scrollPane,BorderLayout.CENTER);
        jlbl2Sobre.setForeground(java.awt.SystemColor.activeCaptionText);
        htmlPane.setVisible(true);
    }
    
    private void initEditorPane() {
    	htmlPane = new JEditorPane();
        htmlPane.setEditable(false);
        htmlPane.setContentType("text/html; charset=windows-1252");
        htmlPane.addHyperlinkListener(this);
    }
    
    private void setEditorPaneContent(URL url) {
        try {
            htmlPane.setPage(url);
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Erro : não consegui abrir arquivo " + url.getPath());
        }
    }
    
    public void hyperlinkUpdate(HyperlinkEvent evt) {
        if (evt.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
            URL url = null;
            String strURL = null;
            try {
                url = evt.getURL();
                strURL = url.toString();
                BrowserControl.displayURL(strURL);
            } catch (Exception e) {
                e.printStackTrace();
                System.out.println("Erro : não consegui abrir o arquivo " + strURL);
            }
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jbtnWelcome1 = new javax.swing.JButton();
        jbtnWelcomeLicenca = new javax.swing.JButton();
        jbtnWelcomeTutoriais = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new SmoothLabel();
        jLabel16 = new SmoothLabel();
        jPanel10 = new javax.swing.JPanel();
        jlbl2Sobre = new SmoothLabel();
        jlbl2Sobre1 = new SmoothLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelWelcome1 = new javax.swing.JPanel();
        jPanelWelcome2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        setMinimumSize(new java.awt.Dimension(631, 450));
        setPreferredSize(new java.awt.Dimension(631, 450));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setPreferredSize(new java.awt.Dimension(560, 35));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/open.gif")));
        jButton2.setMnemonic('V');
        jButton2.setText("Ver Projetos");
        jButton2.setMaximumSize(new java.awt.Dimension(9999, 9999));
        jButton2.setMinimumSize(new java.awt.Dimension(132, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(136, 23));
        jButton2.setRequestFocusEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.add(jButton2);

        jbtnWelcome1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jbtnWelcome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/new.gif")));
        jbtnWelcome1.setMnemonic('N');
        jbtnWelcome1.setText("Novo Projeto");
        jbtnWelcome1.setMaximumSize(new java.awt.Dimension(9999, 9999));
        jbtnWelcome1.setMinimumSize(new java.awt.Dimension(132, 23));
        jbtnWelcome1.setPreferredSize(new java.awt.Dimension(140, 23));
        jbtnWelcome1.setRequestFocusEnabled(false);
        jbtnWelcome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnWelcome1ActionPerformed(evt);
            }
        });

        jPanel3.add(jbtnWelcome1);

        jbtnWelcomeLicenca.setFont(new java.awt.Font("Tahoma", 0, 12));
        jbtnWelcomeLicenca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/license.gif")));
        jbtnWelcomeLicenca.setMnemonic('L');
        jbtnWelcomeLicenca.setText("Ver Licen\u00e7a");
        jbtnWelcomeLicenca.setMaximumSize(new java.awt.Dimension(9999, 9999));
        jbtnWelcomeLicenca.setMinimumSize(new java.awt.Dimension(132, 23));
        jbtnWelcomeLicenca.setPreferredSize(new java.awt.Dimension(136, 23));
        jbtnWelcomeLicenca.setRequestFocusEnabled(false);
        jbtnWelcomeLicenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnWelcomeLicencaActionPerformed(evt);
            }
        });

        jPanel3.add(jbtnWelcomeLicenca);

        jbtnWelcomeTutoriais.setFont(new java.awt.Font("Tahoma", 0, 12));
        jbtnWelcomeTutoriais.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/comments.gif")));
        jbtnWelcomeTutoriais.setMnemonic('T');
        jbtnWelcomeTutoriais.setText("Ver Tutoriais");
        jbtnWelcomeTutoriais.setMaximumSize(new java.awt.Dimension(9999, 9999));
        jbtnWelcomeTutoriais.setMinimumSize(new java.awt.Dimension(132, 23));
        jbtnWelcomeTutoriais.setPreferredSize(new java.awt.Dimension(136, 23));
        jbtnWelcomeTutoriais.setRequestFocusEnabled(false);
        jbtnWelcomeTutoriais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnWelcomeTutoriaisActionPerformed(evt);
            }
        });

        jPanel3.add(jbtnWelcomeTutoriais);

        add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 80));
        jPanel9.setLayout(new java.awt.GridBagLayout());

        jPanel9.setMinimumSize(new java.awt.Dimension(10, 26));
        jPanel9.setPreferredSize(new java.awt.Dimension(10, 26));
        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14));
        jLabel15.setForeground(java.awt.SystemColor.activeCaptionText);
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("versão "+SAPO.VERSION+" - "+SAPO.RELEASEDATE);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel9.add(jLabel15, gridBagConstraints);

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14));
        jLabel16.setForeground(java.awt.SystemColor.controlShadow);
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("versão "+SAPO.VERSION+" - "+SAPO.RELEASEDATE);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 0, 0);
        jPanel9.add(jLabel16, gridBagConstraints);

        jPanel1.add(jPanel9, java.awt.BorderLayout.SOUTH);

        jPanel10.setLayout(new java.awt.GridBagLayout());

        jPanel10.setPreferredSize(new java.awt.Dimension(410, 36));
        jlbl2Sobre.setBackground(new java.awt.Color(255, 255, 255));
        jlbl2Sobre.setFont(new java.awt.Font("Verdana", 1, 26));
        jlbl2Sobre.setForeground(new java.awt.Color(251, 252, 237));
        jlbl2Sobre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl2Sobre.setText("Software para Avalia\u00e7\u00e3o Postural - SAPO");
        jlbl2Sobre.setFocusable(false);
        jlbl2Sobre.setMaximumSize(new java.awt.Dimension(650, 35));
        jlbl2Sobre.setMinimumSize(new java.awt.Dimension(610, 35));
        jlbl2Sobre.setPreferredSize(new java.awt.Dimension(600, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 6;
        jPanel10.add(jlbl2Sobre, gridBagConstraints);

        jlbl2Sobre1.setBackground(new java.awt.Color(255, 255, 255));
        jlbl2Sobre1.setFont(new java.awt.Font("Verdana", 1, 26));
        jlbl2Sobre1.setForeground(javax.swing.UIManager.getDefaults().getColor("controlShadow"));
        jlbl2Sobre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl2Sobre1.setText("Software para Avalia\u00e7\u00e3o Postural - SAPO");
        jlbl2Sobre1.setFocusable(false);
        jlbl2Sobre1.setMaximumSize(new java.awt.Dimension(650, 35));
        jlbl2Sobre1.setMinimumSize(new java.awt.Dimension(610, 35));
        jlbl2Sobre1.setPreferredSize(new java.awt.Dimension(600, 35));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 0, 0);
        jPanel10.add(jlbl2Sobre1, gridBagConstraints);

        jPanel1.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanelWelcome1.setLayout(new java.awt.BorderLayout());

        jPanel2.add(jPanelWelcome1, java.awt.BorderLayout.CENTER);

        jPanelWelcome2.setLayout(new java.awt.GridBagLayout());

        jPanelWelcome2.setPreferredSize(new java.awt.Dimension(279, 60));
        jCheckBox1.setText("N\u00e3o mostrar mais esta tela de boas vindas no futuro");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jPanelWelcome2.add(jCheckBox1, new java.awt.GridBagConstraints());

        jPanel2.add(jPanelWelcome2, java.awt.BorderLayout.SOUTH);

        jPanel4.setPreferredSize(new java.awt.Dimension(50, 10));
        jPanel2.add(jPanel4, java.awt.BorderLayout.WEST);

        jPanel5.setPreferredSize(new java.awt.Dimension(50, 10));
        jPanel2.add(jPanel5, java.awt.BorderLayout.EAST);

        jPanel6.setPreferredSize(new java.awt.Dimension(10, 20));
        jPanel2.add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanel7.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel7, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents

    private void jbtnWelcomeTutoriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnWelcomeTutoriaisActionPerformed
    	BrowserControl.displayURL(SAPO.AJUDAWEB);
    }//GEN-LAST:event_jbtnWelcomeTutoriaisActionPerformed

    private void jbtnWelcomeLicencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnWelcomeLicencaActionPerformed
    	if (jbtnWelcomeLicenca.getText().equals("Ver Licen\u00e7a")) {
    		setEditorPaneContent(sapo.getClass().getResource("/res/licenca.html"));
    		jbtnWelcomeLicenca.setText("Ver Abertura");
    	}
    	else {
    		setEditorPaneContent(sapo.getClass().getResource("/res/welcome.html"));
    		jbtnWelcomeLicenca.setText("Ver Licen\u00e7a");
    	}
    	this.repaint();
    }//GEN-LAST:event_jbtnWelcomeLicencaActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        sapo.user.dados.boasvindas = !jCheckBox1.isSelected();
        sapo.user.escreveDB();
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        sapo.jDialogSAPO.setVisible(false);
        sapo.jDialogSAPO.close();
        sapo.openFromDBDialog();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbtnWelcome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnWelcome1ActionPerformed
        sapo.jDialogSAPO.setVisible(false);
        sapo.jDialogSAPO.close();
        sapo.newProject();
    }//GEN-LAST:event_jbtnWelcome1ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    protected javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanelWelcome1;
    private javax.swing.JPanel jPanelWelcome2;
    private javax.swing.JButton jbtnWelcome1;
    private javax.swing.JButton jbtnWelcomeLicenca;
    private javax.swing.JButton jbtnWelcomeTutoriais;
    private javax.swing.JLabel jlbl2Sobre;
    private javax.swing.JLabel jlbl2Sobre1;
    // End of variables declaration//GEN-END:variables
    
}
