import java.beans.PropertyVetoException;
import javax.swing.JOptionPane;
/*
 * ZoomPanel.java
 *
 * Created on 8 de Fevereiro de 2005, 03:53
 */

/**
 *
 * @author Edison Puig Maldonado
 */

public class ZoomPanel extends javax.swing.JPanel {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 2837606683744116058L;
	SAPO sapo;
   
    /** Creates new form ZoomPanel */
    public ZoomPanel(SAPO sapo) {
        this.sapo = sapo;
        initComponents();
    }
    
    private void slider() {
        if (sapo.jif[sapo.numImg].isMaximum())
            try {
                sapo.jif[sapo.numImg].setMaximum(false);
            } catch (PropertyVetoException e) {
                sapo.errorReport.jtxtErrorReport.append(e.toString()+"\n");
                e.printStackTrace();
                sapo.error = e.getStackTrace();
                for(int k=0; k<sapo.error.length; k++)
                    sapo.errorReport.jtxtErrorReport.append(sapo.error[k].toString()+"\n");
                sapo.errorReport.jtxtErrorReport.append("==========================================="+"\n");
                sapo.jdlgErrorReport.pack();
                sapo.jdlgErrorReport.setVisible(true);      
            }
        sapo.jif[sapo.numImg].zoom = jSlider1.getValue();
        jTextField5.setText(Integer.toString(sapo.jif[sapo.numImg].zoom));
        if (sapo.jif[sapo.numImg].flagImg)
            sapo.showInternalFrameWithImage(sapo.numImg);
        mostraOpcao();
        sapo.mostraZoom();
    }
    
    public void mostraOpcao() {
        switch (sapo.jif[sapo.numImg].zoom) {
            case 10:  jRadioButton10.setSelected(true);  break;
            case 20:  jRadioButton20.setSelected(true);  break;
            case 30:  jRadioButton30.setSelected(true);  break;
            case 40:  jRadioButton40.setSelected(true);  break;
            case 50:  jRadioButton50.setSelected(true);  break;
            case 100: jRadioButton100.setSelected(true); break;
            case 150: jRadioButton150.setSelected(true); break;
            case 200: jRadioButton200.setSelected(true); break;
            case 300: jRadioButton300.setSelected(true); break;
            case 400: jRadioButton400.setSelected(true); break;
            default : jRadioButton0.setSelected(true);
        }
    }
    
    private void zoomNumerico() {
        try{
            int slider = (Integer.valueOf(jTextField5.getText())).intValue();
            if(slider<10) 
                JOptionPane.showMessageDialog(sapo,"O zoom deve ser maior que 10!");
            else 
                jSlider1.setValue(slider);
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(sapo,"Somente números inteiros!");	
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupZoom = new javax.swing.ButtonGroup();
        jpnlZoom = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        jPanel27 = new javax.swing.JPanel();
        jRadioButton400 = new javax.swing.JRadioButton();
        jRadioButton300 = new javax.swing.JRadioButton();
        jRadioButton200 = new javax.swing.JRadioButton();
        jRadioButton150 = new javax.swing.JRadioButton();
        jRadioButton100 = new javax.swing.JRadioButton();
        jRadioButton50 = new javax.swing.JRadioButton();
        jRadioButton40 = new javax.swing.JRadioButton();
        jRadioButton30 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton0 = new javax.swing.JRadioButton();
        jPanel22 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jbtnAjustar = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jbtnZoomOk = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jpnlZoom.setLayout(new java.awt.BorderLayout());

        jPanel18.setLayout(new java.awt.GridBagLayout());

        jPanel26.setLayout(new java.awt.GridBagLayout());

        jSlider1.setMajorTickSpacing(10);
        jSlider1.setMaximum(400);
        jSlider1.setMinimum(10);
        jSlider1.setMinorTickSpacing(5);
        jSlider1.setOrientation(javax.swing.JSlider.VERTICAL);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setFocusable(false);
        jSlider1.setMinimumSize(new java.awt.Dimension(24, 100));
        jSlider1.setPreferredSize(new java.awt.Dimension(30, 250));
        jSlider1.setRequestFocusEnabled(false);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        jSlider1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jSlider1MouseWheelMoved(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        jPanel26.add(jSlider1, gridBagConstraints);

        jPanel27.setLayout(new java.awt.GridBagLayout());

        buttonGroupZoom.add(jRadioButton400);
        jRadioButton400.setText("400 %");
        jRadioButton400.setFocusable(false);
        jRadioButton400.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRadioButton400.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton400ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel27.add(jRadioButton400, gridBagConstraints);

        buttonGroupZoom.add(jRadioButton300);
        jRadioButton300.setText("300 %");
        jRadioButton300.setFocusable(false);
        jRadioButton300.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRadioButton300.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton300ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel27.add(jRadioButton300, gridBagConstraints);

        buttonGroupZoom.add(jRadioButton200);
        jRadioButton200.setText("200 %");
        jRadioButton200.setFocusable(false);
        jRadioButton200.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRadioButton200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton200ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel27.add(jRadioButton200, gridBagConstraints);

        buttonGroupZoom.add(jRadioButton150);
        jRadioButton150.setText("150 %");
        jRadioButton150.setFocusable(false);
        jRadioButton150.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRadioButton150.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton150ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel27.add(jRadioButton150, gridBagConstraints);

        buttonGroupZoom.add(jRadioButton100);
        jRadioButton100.setText("100 %");
        jRadioButton100.setFocusable(false);
        jRadioButton100.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRadioButton100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton100ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel27.add(jRadioButton100, gridBagConstraints);

        buttonGroupZoom.add(jRadioButton50);
        jRadioButton50.setText("50 %");
        jRadioButton50.setFocusable(false);
        jRadioButton50.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRadioButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton50ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel27.add(jRadioButton50, gridBagConstraints);

        buttonGroupZoom.add(jRadioButton40);
        jRadioButton40.setText("40 %");
        jRadioButton40.setFocusable(false);
        jRadioButton40.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRadioButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton40ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel27.add(jRadioButton40, gridBagConstraints);

        buttonGroupZoom.add(jRadioButton30);
        jRadioButton30.setText("30 %");
        jRadioButton30.setFocusable(false);
        jRadioButton30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRadioButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton30ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel27.add(jRadioButton30, gridBagConstraints);

        buttonGroupZoom.add(jRadioButton20);
        jRadioButton20.setText("20 %");
        jRadioButton20.setFocusable(false);
        jRadioButton20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRadioButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton20ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel27.add(jRadioButton20, gridBagConstraints);

        buttonGroupZoom.add(jRadioButton10);
        jRadioButton10.setText("10 %");
        jRadioButton10.setFocusable(false);
        jRadioButton10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel27.add(jRadioButton10, gridBagConstraints);

        buttonGroupZoom.add(jRadioButton0);
        jRadioButton0.setText("?");
        jRadioButton0.setFocusable(false);
        jRadioButton0.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jPanel27.add(jRadioButton0, gridBagConstraints);

        jPanel26.add(jPanel27, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel18.add(jPanel26, gridBagConstraints);

        jPanel22.setMinimumSize(new java.awt.Dimension(70, 40));
        jLabel11.setText("Zoom =");
        jPanel22.add(jLabel11);

        jTextField5.setColumns(4);
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jPanel22.add(jTextField5);

        jLabel14.setText("%");
        jPanel22.add(jLabel14);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        jPanel18.add(jPanel22, gridBagConstraints);

        jbtnAjustar.setText("Ajustar");
        jbtnAjustar.setMaximumSize(null);
        jbtnAjustar.setMinimumSize(new java.awt.Dimension(70, 23));
        jbtnAjustar.setPreferredSize(new java.awt.Dimension(70, 23));
        jbtnAjustar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAjustarActionPerformed(evt);
            }
        });

        jPanel28.add(jbtnAjustar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        jPanel18.add(jPanel28, gridBagConstraints);

        jpnlZoom.add(jPanel18, java.awt.BorderLayout.CENTER);

        jbtnZoomOk.setText("OK");
        jbtnZoomOk.setMaximumSize(null);
        jbtnZoomOk.setMinimumSize(new java.awt.Dimension(70, 23));
        jbtnZoomOk.setPreferredSize(new java.awt.Dimension(70, 23));
        jbtnZoomOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnZoomOkActionPerformed(evt);
            }
        });

        jPanel21.add(jbtnZoomOk);

        jpnlZoom.add(jPanel21, java.awt.BorderLayout.SOUTH);

        add(jpnlZoom, java.awt.BorderLayout.NORTH);

    }
    // </editor-fold>//GEN-END:initComponents

    private void jbtnAjustarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAjustarActionPerformed
        jSlider1.setValue(sapo.calculaZoomOtimo(
                sapo.jif[sapo.numImg].getRenderedImage().getWidth(), 
                sapo.jif[sapo.numImg].getRenderedImage().getHeight()));
    }//GEN-LAST:event_jbtnAjustarActionPerformed

    private void jSlider1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jSlider1MouseWheelMoved
        if(evt.getWheelRotation()<0)
            jSlider1.setValue(jSlider1.getValue()+5);
        else
            jSlider1.setValue(jSlider1.getValue()-5);
    }//GEN-LAST:event_jSlider1MouseWheelMoved

    private void jRadioButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton40ActionPerformed
        jSlider1.setValue(40);
    }//GEN-LAST:event_jRadioButton40ActionPerformed

    private void jRadioButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton30ActionPerformed
        jSlider1.setValue(30);
    }//GEN-LAST:event_jRadioButton30ActionPerformed

    private void jRadioButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton20ActionPerformed
        jSlider1.setValue(20);
    }//GEN-LAST:event_jRadioButton20ActionPerformed

    private void jRadioButton400ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton400ActionPerformed
        jSlider1.setValue(400);
    }//GEN-LAST:event_jRadioButton400ActionPerformed

    private void jRadioButton300ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton300ActionPerformed
        jSlider1.setValue(300);
    }//GEN-LAST:event_jRadioButton300ActionPerformed

    private void jRadioButton200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton200ActionPerformed
        jSlider1.setValue(200);
    }//GEN-LAST:event_jRadioButton200ActionPerformed

    private void jRadioButton150ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton150ActionPerformed
        jSlider1.setValue(150);
    }//GEN-LAST:event_jRadioButton150ActionPerformed

    private void jRadioButton100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton100ActionPerformed
        jSlider1.setValue(100);
    }//GEN-LAST:event_jRadioButton100ActionPerformed

    private void jRadioButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton50ActionPerformed
        jSlider1.setValue(50);
    }//GEN-LAST:event_jRadioButton50ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        jSlider1.setValue(10);
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        slider();
    }//GEN-LAST:event_jSlider1StateChanged

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        zoomNumerico();
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jbtnZoomOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnZoomOkActionPerformed
        zoomNumerico();
        try{
			sapo.jif[sapo.numImg].setMaximum(false);
		}catch(Exception e){};
        sapo.showInternalFrameWithImage(sapo.numImg);
    }//GEN-LAST:event_jbtnZoomOkActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupZoom;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    public javax.swing.JRadioButton jRadioButton0;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton100;
    private javax.swing.JRadioButton jRadioButton150;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton200;
    private javax.swing.JRadioButton jRadioButton30;
    private javax.swing.JRadioButton jRadioButton300;
    private javax.swing.JRadioButton jRadioButton40;
    private javax.swing.JRadioButton jRadioButton400;
    private javax.swing.JRadioButton jRadioButton50;
    public javax.swing.JSlider jSlider1;
    public javax.swing.JTextField jTextField5;
    private javax.swing.JButton jbtnAjustar;
    private javax.swing.JButton jbtnZoomOk;
    private javax.swing.JPanel jpnlZoom;
    // End of variables declaration//GEN-END:variables
    
}
